### ISSUE TITLE
the TB add-on is not auto-installed on Manjaro Linux using AUR

### ISSUE THREAD

**Issue by atomGit** [Ximi1970/systray-x#103]
i installed systray-x from the AUR on Manjaro Linux but had to install the TB add-on manually - is this the intended procedure?

**Comment by Ximi1970** [comment]
I do not maintain the AUR install package. I do not know what or how it is installed.
If you want my support please use my repository on the opensuse servers.

**Comment by Ximi1970** [comment]
Sorry I do not know who maintains the Manjaro package. A package should normally install the xpi add-on and the companian app.

**Comment by angrysquirell** [comment]
Here's the pkgbuild, imho defective, outdated with unsafe permissions, probably without path change in app/SysTray_X.json file: _/path/to/native-messaging/app -> /usr/bin_
