### ISSUE TITLE
Unread mail count not useful at the moment with several accounts and folders

### ISSUE THREAD

**Issue by araujorm** [Ximi1970/systray-x#104]
Hello.

The unread mail count seems to only check the Inbox folders of my accounts, which is not useful for me since I have some accounts that are shared mailboxes that I can't really control and can't just go there and mark as read.

Also, lots of messages that I have go to specific folders via server-side sieve controlled filters (most of them belong to a support system and I will never read, but want to have so I can search them if needed), so usually I am only interested in a few folders, and not all are top INBOX ones.

What would make sense would be to give some option to chose which folders should be taken into account when displaying the total count. Thundertray (I think that was the one) used to do that elegantly by giving the option to only take into account the folders that are "marked as favorite" (in thunderbird, right click a folder and check that option). Is it possible to add that to systray-x?

Thanks in advance.

**Comment by Ximi1970** [comment]
You can configure your accounts and folders in the preferences menu of the add-on in Thunderbird. I will not send any account and folder info to the companion app (and the preference menu there) for privacy reasons.

**Comment by araujorm** [comment]
Oh, I missed it... many thanks, that's precisely what I needed.

**Comment by Ximi1970** [comment]
The new preference dialog of the app makes it a bit more clearer, but is not yet in a release.
