### ISSUE TITLE
No Installer for KDE on Manjaro(Arch) ?

### ISSUE THREAD

**Issue by mfreeman-xtivia** [Ximi1970/systray-x#108]
Trying to install on KDE Manjaro, which is Arch.

Downloaded **SysTray-X-1.0.8.0-0-Arch-x86_64-Minimal-install.sh** but it complains during the install and says 

Please use the SysTray-X-1:0.8.0-0-Arch-x86_64-KDE-install.sh installer.
This setup will not work.

Unfortunately I can find no such script in the list of available downloads

**Comment by lectrode** [comment]
```
sudo pacman -S yay
yay -S systray-x-git
```

this works for me. it's also in the [ReadMe](https://github.com/Ximi1970/systray-x#arch)

**Comment by Ximi1970** [comment]
Was probably an error in my build scripts. But please try to use a repository. It will be more up to date.
The manual installer depends on the state of Manjaro/Arch at the moment of the release and will not be updated.
And with Arch or any other rolling release the manual installer will become obsolete really quick.
I am planning to scrap the manual installers...
