### ISSUE TITLE
Changes of icon style in tray are applied only after a Thunderbird restart

### ISSUE THREAD

**Issue by rwiesbach** [Ximi1970/systray-x#110]
fedora 34 x64, Xfce x11, TB 91.3.0 x64
Add-on version 0.8.0
App version unknown, current from repo.
Install type: via fedora 34 repo as shown in repo

Is it intended that making and saving the changes does not alter the icon and only a TB restart make the icon change? I would expect that at least saving it would also apply it without restarting the TB. If this is not intended, consider this a FR rather than a bug. Thank you.

**Comment by Ximi1970** [comment]
Sorry, not supported anymore. Please upgrade your system to the latest fedora.
