### ISSUE TITLE
does not read / write settings, can't change options

### ISSUE THREAD

**Issue by jeancremers** [Ximi1970/systray-x#111]
Somehow it does not read / write settings. For instance the icon size shows up as 0, mail accounts is empty, I can't set an icon with a number or change color. The plain thunderbird icon does show up on new mail though but i can't change it to a numbered one. This is all working fine in the virtual box instance, but not on my plain windows 10. I have a unified inbox, could that be it?
Bedankt.

**Comment by Ximi1970** [comment]
See #4, I really cannot do anything with this. I am trying to support more then 20 distros and they all tend to have they're own quirks. Be more specific on the system used.
