### ISSUE TITLE
Missing/invisible 'new mail icon'

### ISSUE THREAD

**Issue by mjeveritt** [Ximi1970/systray-x#112]
* Ubuntu 18.04 LTS
* KDE
* XDG_SESSION_TYPE = x11
* Thunderbird 91.5.0 (64-bit)
* Addon: 0.8.0
* App version: 0.8.0 build 770
* Install type: PPA `https://download.opensuse.org/repositories/home:/Ximi1970:/Mozilla:/Add-ons/xUbuntu_18.04/`
* Qt: default `(5.9.5?)`

Selecting 'New mail icon' always shows a black envelope, irrespective of Light/Dark theme setting. This is invisible against a dark-coloured panel/taskbar.
![image](https://user-images.githubusercontent.com/11815838/151271930-7fd028ba-4d56-47d6-8cc5-524604c25fed.png)<img src="https://user-images.githubusercontent.com/11815838/151273025-730883d6-af24-4902-8bb6-ae56cdbe9a66.png" width="200">

**Comment by whtyger** [comment]
@mjeveritt It seems that Light/Dark setting affects only the color of unread mail counter.
If you wish to get more distinct icon, you can set "Custom icon" and use the icon from Breeze Dark theme. It is located here: `/usr/share/icons/breeze-dark/actions/22/mail-mark-unread.svg`

**Comment by Ximi1970** [comment]
Changed the "theme" item into a invert icon option. Not yet in a release.
