### ISSUE TITLE
Betterbird support?

### ISSUE THREAD

**Issue by scruel** [Ximi1970/systray-x#114]
I wonder can this project support a fork of Thunderbird called [Betterbird](https://www.betterbird.eu)?
It's cool to have the multi-line view on the mail list, and I'd like to use it to replace the official version in the future.
But is still not support the tray function on Linux currently, thanks!

**Comment by Ximi1970** [comment]
It seems to be working just fine with the develop branch. Just follow the building instruction in the README.md but change the last cp from the thunderbird profile dir to the betterbird profile dir (if they even changed that directory)   
You can also install the xpi in the add-ons manager / Extensions page using the install from file option.

**Comment by Ximi1970** [comment]
You can also install the addon package for your distro. This will also install thunderbird of course.  
After installation find the spot were the xpi file was installed and install this file using the install from file option in betterbird.

**Comment by Ximi1970** [comment]
Added betterbird support. Not yet in a release.

**Comment by mohamedhagag** [comment]
Hi all,
this is not working with betterbird anymore as the companion app is looking for thunderbird specific version as I got from reading the code.

How can we change this to work with betterbird ?

Regards
