### ISSUE TITLE
Systray-X doesn't work on Thunderbird 102.0

### ISSUE THREAD

**Issue by giwrgosmant** [Ximi1970/systray-x#117]
**Describe the bug**
Systrax-X doesn't work since upgrading on Thunderbird 102.0.
I hope for a quick update on systray-x. It's really useful, can't use Thunderbird without it. 🤞

**Comment by Ximi1970** [comment]
I will make a new release version this week. Thnx for the heads up on the new release. Downloaded the 102.0b8 a week ago to check every thing.
I will not be able to test all the platforms as I used to do. Just takes too long.

I will create the release and build all the new packages a.s.a.p. and hope for the best :smile:

**Comment by giwrgosmant** [comment]
> I will make a new release version this week. Thnx for the heads up on the new release. Downloaded the 102.0b8 a week ago to check every thing. I will not be able to test all the platforms as I used to do. Just takes too long.
> 
> I will create the release and build all the new packages a.s.a.p. and hope for the best 😄

Thank you very much! You are awesome! Keep it up 😎
I use win11 so I can test it when u release it 🤓
