### ISSUE TITLE
"New mail logic" commit breaks mail counter in tray icon (Arch, multiple install mehods)

### ISSUE THREAD

**Issue by nicolamori** [Ximi1970/systray-x#118]
**Describe the bug**
Commit 94b41e28d283aef225ce14c883192d72e9833047 ("New mail logic") freezes the mail counter on the tray icon. The mail count is not updated on new/unread mails. Previous commit shows correct behavior.

**To Reproduce**
Build and install commit 94b41e28d283aef225ce14c883192d72e9833047. Wait for a new mail to arrive or mark one as unread

**Expected behavior**
The mail counter should be increased

**Desktop (please complete the following information):**
 - OS: Archlinux
 - Architecture: 64 bit
 - Desktop type / Window Manager: Plasma desktop, both X11 and Wayland sessions
 - Thunderbird version and arch: 91.10.0 (64-bit)
 - Run `echo $XDG_SESSION_TYPE` in a terminal and report the results: x11
 - Add-on version 
 - App version
 - Install type: self-built using Arch build system
 - Used Qt library (default system repository, other OBS repo, self-compiled, Qt online installer): 5.15.5

**Comment by Ximi1970** [comment]
I cannot replicate your problem. Everything seems to be working with the latest develop version.
But I see you tried every install option and that is a bad idea.  
Things are getting installed in different places with the different install options and will very likely cause unpredictable results when used al together.
Try cleaning your system of all systray-x files, look in yout thunderbird profiles and firefox settings dir, the system dirs of thunderbird and firefox.  

Please stick to 1 type of installation. And please use a repository. This way the package will prevent you from updating to an incompatible TB version until I check the comatibility a bit.

**Comment by nicolamori** [comment]
@Ximi Sorry, I misinterpreted the bug report template and I didn't remove the install options I didn't use. Actually I used only one method, namely building and installing the package using the Archlinux build system. I updated my original post, sorry again for the inconvenience.

**Comment by nicolamori** [comment]
@Ximi1970 I just updated Thunderbird from 91.10.0 to 91.11.0 and systray-x to 0.9.0 (commit 19581e0c2b2000fbd58d5534b0fd0eae980260ba) and everything works again. Probably I stumbled upon a problematic git commit that has been fixed in the new release. Thanks for the support!
