### ISSUE TITLE
Win11 Close to Minimize doesn't work on latest version.

### ISSUE THREAD

**Issue by giwrgosmant** [Ximi1970/systray-x#119]
**Describe the bug**
Close to minimize doesn't work on latest Thunderbird 102.0 with latest release of systray-x. When I press X it closes the window (exit app) instead of minimize. However I've set the option to settings. I've tried with both options Minimize main, close childer and Minimize all.

**Expected behavior**
It should minimize to tray when I press X and I close the window.

**Screenshots**
![2022-07-04 04_30_58-SysTray-X Preferences](https://user-images.githubusercontent.com/51835189/177066581-e1dd916f-506e-4798-965d-f95b24d74963.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Architecture: 64 bit
 - Thunderbird version and arch (Tb 102.0 64 bit)
 - Add-on version: latest 0.9.0
 - App version: latest 0.9.0

**Comment by Ximi1970** [comment]
There is also still a  bug in the windows installer If you updated the addon from 0.8.0 to 0.9.0.
You need the manually install the .xpi from the c:/program files/SysTray directory.
Do not know if this solves your problem, see also: #98
My windows installs seem to work now.

**Comment by giwrgosmant** [comment]
I used the installation "just for me" so I used the .xpi from AppData. Unfortunately didn't worked.
I've uninstalled completely the systray-x and installed it again, but still the same issue. Strange, all other versions working fine 🤔

**Comment by giwrgosmant** [comment]
> There is also still a bug in the windows installer if you did an update off the addon from 0.8.0 to 0.9.0. You need the manually update the .xpi from the c:/program files/SysTray directory. Do not know if this solves your problem, see also: #98 My windows installs seem to work now.

I used the installation "just for me" so I used the .xpi from AppData. Unfortunately didn't worked.
I've uninstalled completely the systray-x and installed it again, but still the same issue. Strange, all other versions working fine 🤔

**Comment by giwrgosmant** [comment]
> Looks like my close button fix wasn't really a fix :-) Reverted the "fix". I will create a patch release after some extra testing.

Thank you. I really appreciate the time you spent on this project. 👍

**Comment by Ximi1970** [comment]
New release!

**Comment by giwrgosmant** [comment]
> New release!

Thank you very much. It seems fixed in latest version. 👍
