### ISSUE TITLE
Duplicated icon with 0.9.0

### ISSUE THREAD

**Issue by lgbaldoni** [Ximi1970/systray-x#120]
**Describe the bug**
I can see two icons in the tray, one with unread mails and a plain one.

**To Reproduce**
Upgrade from 0.8.0 and launch.
 on openSUSE Leap 15.4 (TB 91.10.0)

**Expected behavior**
Seeing just one icon

**Screenshots**
![My tray](https://user-images.githubusercontent.com/1450716/177111898-245544aa-13ad-4179-b209-6cd1ac28bb6f.jpg)

**Desktop (please complete the following information):**
 - OS: openSUSE Leap 15.4
 - Architecture x86_64
 - Desktop type / Window Manager plasma 5.24.4
 - Thunderbird version and arch TB 91.10.0 x86_64
 - Run `echo $XDG_SESSION_TYPE` in a terminal and report the results x11
 - Add-on version 0.9.0
 - App version No idea
 - Install type: OBS repository  
 - Used Qt library default system repository

**Additional context**
Nothing else to add

**Comment by lgbaldoni** [comment]
Also the main window won't close when clicking on the close button.

**Comment by Ximi1970** [comment]
Maybe two instance of Thunderbird running?
And the problem with the close button seems something due the last suse thunderbird package. The binary package of thunderbird seems to work without any problem. Bit confused again here.

**Comment by lgbaldoni** [comment]
> Maybe two instances of Thunderbird running? And the problem with the close button seems something due the last suse thunderbird package. The binary package of thunderbird seems to work without any problem. Bit confused again here.

First of all it's a somewhat intermittent problem. Also closing (right-click/quit) from the tray icon works only if I do that on the numberless icon. Closing from the other one will merely remove that icon.

```
> ps ax|grep thund
19590 pts/4    Sl+    0:02 /usr/lib64/thunderbird/thunderbird-bin
19730 pts/4    Sl+    0:00 /usr/lib64/thunderbird/thunderbird-bin -contentproc -childID 1 -isForBrowser -prefsLen 1 -prefMapSize 304793 -jsInit 285636 -parentBuildID 20220525135609 -appdir /usr/lib64/thunderbird 19590 tab
19774 pts/4    Sl+    0:00 /usr/lib64/thunderbird/thunderbird-bin -contentproc -childID 2 -isForBrowser -prefsLen 248 -prefMapSize 304793 -jsInit 285636 -parentBuildID 20220525135609 -appdir /usr/lib64/thunderbird 19590 tab
19880 pts/3    S+     0:00 grep --color=auto thund
```

**Comment by lgbaldoni** [comment]
Should I try and reset prefs?

**Comment by Ximi1970** [comment]
I also triggered the double icon and one instance of TB but indeed two instances of SysTray-X.....I am baffled.

**Comment by Ximi1970** [comment]
Now one icon but two config icons in Extension page. It is getting very strange.

![image](https://user-images.githubusercontent.com/859953/177206013-2b9cb5d8-cd6b-4a10-bd1e-68b1ee576986.png)

**Comment by Ximi1970** [comment]
Normally I am using 15.4 and the Mozilla repo for the latest version. Never seen this before. More investigation needed.

**Comment by lgbaldoni** [comment]
Do you think it's safe to restore the old version?

**Comment by mjeveritt** [comment]
Possibly unrelated, but earlier today I lost the mail icon completely from the system tray .. a restart of TB brought it back though, nothing else seemed to help ?! I think the counter had reset to zero, but how it unloaded itself, I have no clue ..

**Comment by Ximi1970** [comment]
Looks like my fix for the close button problem caused the problems. I reverted the fix but cleaned the code a bit and merged it into develop branch. Will do some extra testing before making a patch release.

**Comment by Ximi1970** [comment]
New release!
