### ISSUE TITLE
[0.9.1] Main window won't minimize when clicking on close.

### ISSUE THREAD

**Issue by lgbaldoni** [Ximi1970/systray-x#122]
**Describe the bug**
Clicking on the close button won't elicit any response.

**To Reproduce**
* Install 0.9.1 from home:Ximi1970:Mozilla:Add-ons/systray-x
* Run Thunderbird
* Click the close button

**Expected behavior**
The window disappearing

**Screenshots**

**Desktop (please complete the following information):**
 - OS: openSUSE Linux Leap 15.4
 - Architecture 64 bit
 - Desktop type / Window Manager KDE Plasma5
 - Thunderbird version and arch Thunderbird 91.11.0 x86_64
 - Run `echo $XDG_SESSION_TYPE` in a terminal and report the results x11
 - Add-on version 0.9.1
 - App version n/a
 - Install type: OBS repository
 - Used Qt library 5.15.2 from system repository
  
**Additional context**

**Comment by Ximi1970** [comment]
Is the titlebar disabled?

**Comment by Ximi1970** [comment]
I get the error message "Window listener for extension + 'closeButtonListener' already registered" ttilebat disabled and logining in.
When I quit and start TB again it works.

**Comment by lgbaldoni** [comment]
> I get the error message "Window listener for extension + 'closeButtonListener' already registered" ttilebar disabled and logiing in.

Sorry, where? Should I open a debug window or something?

**Comment by Ximi1970** [comment]
In Tb -> Open the menu -> View -> Toolbars -> Toolbat Layout... -> Left bottom, checkbox Titlebar

**Comment by lgbaldoni** [comment]
Nothing happens in the debug console whenever I click on close.

**Comment by Ximi1970** [comment]
Could you try the package in this repo:

```sudo zypper ar -f https://download.opensuse.org/repositories/home:/Ximi1970:/Mozilla:/Add-ons:/Staging:/Test3/15.4/ SysTray-X-Test3```
```sudo zypper in systray-x```

Make sure this version is installed:
```systray-x-0~git20220711.bc9df9a-150400.30.1.x86_64.rpm```

I removed an old? call. There is still an error thrown when disabling the add-on but that seems to have no impact.

**Comment by lgbaldoni** [comment]
> `systray-x-0~git20220711.bc9df9a-150400.30.1.x86_64.rpm`

Much better, thanks!
