### ISSUE TITLE
Can't close Thunderbird from the tray

### ISSUE THREAD

**Issue by lgbaldoni** [Ximi1970/systray-x#123]
**Describe the bug**
Exiting the app from the tray closes only the icon and not Thunderbird

**To Reproduce**
Right-click on the tray icon and select Exit

**Expected behavior**
The Thunderbird application to close as well

**Screenshots**

**Desktop (please complete the following information):**
 - OS: openSUSE Linux Leap 15.4
 -  Architecture 64 bit
 -  Desktop type / Window Manager KDE Plasma5
 -  Thunderbird version and arch Thunderbird 91.11.0 x86_64
 -  Run echo $XDG_SESSION_TYPE in a terminal and report the results x11
 -  Add-on version 0.9.1
 -  App version n/a
 -  Install type: OBS repository
 -  Used Qt library 5.15.2 from system repository

**Additional context**
Possibly related to https://github.com/Ximi1970/systray-x/issues/120 ?

**Comment by Ximi1970** [comment]
Is the titlebar disabled?

**Comment by Ximi1970** [comment]
I cannot repliicate this one (yet)...

**Comment by lgbaldoni** [comment]
> Is the titlebar disabled?

Where do I check?

BTW, after a few open and close the second icon is back.

**Comment by Ximi1970** [comment]
Also did not see the double icon (yet) but seems that it is caused when the close is badly intercepted.

Titlebar: In Tb -> Open the menu -> View -> Toolbars -> Toolbat Layout... -> Left bottom, checkbox Titlebar.
Debug: In Tb -> Open the menu -> Tools -> Developer Tools -> Error console
And / or: Tb -> Open the menu -> Tools -> Developer Tools -> Debug Addons -> Select the "Inspect of SysTray-X -> console tab

**Comment by lgbaldoni** [comment]
Titlebar is on. I couldn't reproduce this anymore but now I'm stuck with two icons.

[This](https://github.com/Ximi1970/systray-x/files/9079595/tb_systray_x_091_debugging_console.txt)  is what I see in the debugging console, no apparent error in the extension-specific console.

Plus, I'm now stuck with two icons. Could it be switching back and forth between 0.8.0 and 0.9.1 is leaving cruft? Should I try a clean profile?

**Comment by Ximi1970** [comment]
I think I found the problem and can easily generate the double icon. Disabling (from the TB extension page) / closing the addon is not oke. It triggers an exception in the shutdown boostrap. Will have to look into that.
