### ISSUE TITLE
Select acounts to display

### ISSUE THREAD

**Issue by zhum** [Ximi1970/systray-x#126]
**Is your feature request related to a problem? Please describe.**
I have several mail accounts and want to see summary count only for two of them.

**Describe the solution you'd like**
Make an option in Systray-X for selecting accounts, used for count in this plugin (or excluded from count, if it is more convenient for developer).

**Describe alternatives you've considered**
There are no real alternatives :)

**Additional context**
None.

**Comment by mjeveritt** [comment]
This does already exist. Go into your Thunderbird Settings/Addons and Themes and select Systray-X and pick the wrench icon to configure the plugin. Pick the 'Mail' tab from the dialog presented.

Here is my settings for comparison. I'm not 100% sure that Systray-X is paying correct attention to this, but I've just changed settings, so any false-positives I was experiencing could well be erroneous!! 
![Screenshot_20220802_170612sanitised](https://user-images.githubusercontent.com/11815838/182423545-6fbb6419-0b24-4fcd-9c84-f1c18ae593cf.png)

**Comment by zhum** [comment]
Thank you! Worked well!
