### ISSUE TITLE
Incorrect behaviord with multiple windows and close pressed on main - a)minimize active children too, b)restore minimized children.

### ISSUE THREAD

**Issue by Pe3ucTop** [Ximi1970/systray-x#127]
First of all - thanks for add-on.

Bug description:
"Minimize to tray" + "Minimize main, close children"
 incorrect behavior when Thunderbird opened with multiple windows and "Close" pressed on main one
a) all not minimized  children get minimized too 
- expected (my opinion) this close should be only per single window
- it prevent from easy closing children windows, because those get hidden/minimized too
- even "Minimize main, close children" confused me at that moment, imagined that "children got closed and main minimized"

b) if some of children get minimized before  (with minimize button), those get restored (this behavior is not always/random)
- this is definitely abnormal, I'm going to minimize one window but one or more other get restored(pop-up).
- this related to #45 because I'm too prefer to minimize to task bar, but "close" to system tray

This is also partial ThunderBird bug,  because all children windows looks like main one.
Maybe there is option to disable "main tab" in children window?

**Comment by Ximi1970** [comment]
New release.
