### ISSUE TITLE
Systray-x 0.9.2.r11.gdb5b472 is disabled and reported as incompatible with Thunderbird 102.2.0

### ISSUE THREAD

**Issue by angrysquirell** [Ximi1970/systray-x#128]
System: Arch Linux, up to date
Desktop environment: Xfce

Addon does not start with mentioned version, marked as incompatible.

It's self build package with pkgbuild as follows:
https://0x0.st/opaQ.txt
File list:
https://0x0.st/opa1.txt

In addition Thunderbird's addons menu reports version other as compiled package, 0.8.0, last updated on April 3rd, 2022.

**Comment by angrysquirell** [comment]
Culprit was a **local** copy located in ~/.thunderbird/extensions/*.xpi in opposite to newest *.xpi version correctly located in /usr/lib/thunderbird/extensions. 

Works like a charm :+1:

**Comment by atomGit** [comment]
confirmed - deleting the add-on in /extensions and restarting TB works

perhaps this issue should be re-opened for a while just for visibility sake???

thanks @angrysquirell
