### ISSUE TITLE
PGP signature invalid on Arch repo

### ISSUE THREAD

**Issue by PLefebvreBJO** [Ximi1970/systray-x#129]
Just followed the steps to add your repository to Arch but it seems the PGP key is deprecated or the signature corrupted.

AUR version is too old and last thunderbird update (102.2) breaks it.

Will build the git version meanwhile. Thanks for your work.

pacman stderr : 

```
error: systray-x: signature from "home:Ximi1970 OBS Project <home:Ximi1970@build.opensuse.org>" is invalid
:: File /var/cache/pacman/pkg/systray-x-1:0.9.2-0-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).

```

**Comment by Ximi1970** [comment]
Should be solved. All keys and packages are updated.
Please keep in mind that at the moment gnome-extensions are not working in Arch, so there is no SysTray-X icon in GNOME.
I just love rolling release /s
