### ISSUE TITLE
Drag-n-drop broken

### ISSUE THREAD

**Issue by zhum** [Ximi1970/systray-x#131]
**Describe the bug**
With systray-x on, any mail drag into folder fails in ~1sec, drag action just cancels and then no mail can be dragged .

**To Reproduce**
Click and hold any mail, try to drag it into other folder. Drag is started and almost immediately cancels.

**Expected behavior**
Mail transparent copy follows the mouse cursor, after mouse button release over the folder the mail is moved into it

**Screenshots**
No screenshots...

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Architecture 64
 - Cinnamon
 - TB 91.13.0 (64-bit)
 - echo $XDG_SESSION_TYPE => x11
 - Add-on version 0.8.0
 - App version 0.9.2-0
 - Install type: github repository build (https://download.opensuse.org/repositories/home:/Ximi1970:/Mozilla:/Add-ons/xUbuntu_21.04), systray-x-gnome
 - Used Qt library - default system repository

**Comment by Ximi1970** [comment]
Solved in the latest release
