### ISSUE TITLE
[Improvement] Add a "new mail" indicator to the unread mail counter (show both unread and new)

### ISSUE THREAD

**Issue by benintech** [Ximi1970/systray-x#134]
Right now in the mail counter settings we can choose between "Unread mails" or "New mails".

I think it would be nice to have both, one way or another.

An idea would be to show the "unread mail" number, but with an additional sign if there are also some new mails (like the yellow/orange star that Thunderbird puts in front of its folder icon). That info would then be interpreted as "you have _x_ unread mails, and some of them are new".

Another idea would be, for people like me who use the blank mail notification icon, to modify that icon's color : white (like it is now) if there are no new mails, and light yellow if there are new ones.

**Comment by Ximi1970** [comment]
Add a new indicator option, rond icon, star icon or shading of the base icon (color can be chosen). It is available in the git, develop branch. Will be add automaticaly when I create a new release. (Next week I think, still trying to find a reported count bug)
