### ISSUE TITLE
[Feature] Launch a command when quitting Thunderbird

### ISSUE THREAD

**Issue by benintech** [Ximi1970/systray-x#135]
It would be handy to be able to launch a command when quitting Thunderbird.

When Thunderbird is closed, I like to have a mail notification daemon (like [mailnag](https://github.com/pulb/mailnag)) running in the background, so I can be notified when new mails arrive on the server, even with Thunderbird closed.

Right now I have a cronjob that checks every minutes if Tunderbird is running, and if not it launches mailnag. It would be cleaner to launch mailnag whenever I quit TB.

Is it possible to add the option to launch a command when quitting Thunderbird ?

**Comment by Ximi1970** [comment]
Added a start and close command option. Available in the git, develop. It will be added in the next release. First I need to refactor the unread / new handling for another request.
