### ISSUE TITLE
Bookmarks Folder Contents Cluttered Over Bookmarks Bar

### ISSUE THREAD

**Issue by flexid2000** [Ximi1970/systray-x#136]
**Bug**
Booksmarks from a folder in the bookmarks bar are occasionally displayed outside the folder in the bar.

**To Reproduce**
Create a folder filled with subfolders and bookmarks in the bookmarks bar. Occasionally, all bookmarks including those from the folder and the subfolders are lined up in the bookmarks bar. It is not predictable when it will happen.

**Expected behavior**
The contents of the bookmarks folder and the subfolders should stay where they belong to.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ArchLinux
 - Architecture: 64 bit
 - Desktop Environment: Xfce and LXQt
 - Thunderbird version: 102.4.2
 - XDG_SESSION_TYPE: x11
 - SysTray-X version: SysTray-X-1.0.9.2-0-Arch-x86_64-Minimal
 - Install type: script installer
 - Used Qt library: default system repository

**Additional context**

**Comment by Ximi1970** [comment]
Uh, bookmarks?
Are you posting in the right project?
