### ISSUE TITLE
[Feature] Change the system-wide SysTray-X configuration using a text file to get a default configuration

### ISSUE THREAD

**Issue by PS1Online** [Ximi1970/systray-x#139]
Currently the only way to do this is by changing the files within the plugin itself (plugin.xpi) but during the upgrade this configuration would be overwritten and therefore not the right way to change a default configuration.
From the next version of systray-x is it possible to change the default configuration of systray-x via a text file in a system folder?

**Comment by Ximi1970** [comment]
I did not change the Systray-X storage anymore see upgrading should not delete the old preferences anymore.

**Comment by Ximi1970** [comment]
It is impossible to read a file outside the TB addon namespace. It could be done using the companion app but then the settings will be read to late for some actions and it would be a terrible task to determine the right config at the right time.
