### ISSUE TITLE
Systray-x checks for unread messages instead of newly received messages

### ISSUE THREAD

**Issue by loveless90** [Ximi1970/systray-x#14]
Would it be possible to check for newly received (the blue highlighted with yellow asterisk) messages instead of unread messages. The way it works now, you can mark a message as unread and it will detect it as new message

Tested with version 0.1.3

**Comment by Ximi1970** [comment]
Sorry that is not possible with the current TB Api interface. The filter can only get unread messages.

https://thunderbird-webextensions.readthedocs.io/en/68/messages.html

see query part.

**Comment by loveless90** [comment]
Ok. Thank you for your quick reply.

**Comment by hockeymikey** [comment]
Should be reopened for tracking: https://developer.mozilla.org/en-US/docs/Mozilla/Thunderbird/Thunderbird_extensions/HowTos/Folders_and_message_lists#Check_for_New_Mail
Checking for new mail is a planned feature, so would be good to keep on the radar when the day comes that it is added.
