### ISSUE TITLE
If I try to change the "Number color" from the "Preferences/Icon" menu, SysTray-X freezes

### ISSUE THREAD

**Issue by PS1Online** [Ximi1970/systray-x#140]
I have installed SysTray-X 0.9.2 (latest version) system wide using your Ubuntu 22.04 repository.
Ubuntu 22.04 LTS Desktop 64-bit using GNOME Shell 42.5 with Xorg.

![simplescreenrecorder-2022-11-25_12 00 31](https://user-images.githubusercontent.com/28962652/203971264-c7982480-5df7-466a-87c8-25642b1bdbc9.gif)

**Comment by 2shrestha22** [comment]
Actually it is not freezing but it opens color picker below the systray-x window and systray windows always stays on top. Same happened to me in KDE.

**Comment by Ximi1970** [comment]
Fixed in git, develop branch. Will soon be added to the next release.
