### ISSUE TITLE
Repo setup for Fedora 37

### ISSUE THREAD

**Issue by Entrepreneur-AJ** [Ximi1970/systray-x#142]
With Fedora 35 being EOL and Fedora 37 now out of beta. Would it be possible to update the repo for users whom have upgraded to F37.

**Comment by maxwai** [comment]
Just so you know:

the repo is available for F37. It is just not yet in the README but you can access the repo at:

https://download.opensuse.org/repositories/home:/Ximi1970:/Mozilla:/Add-ons/Fedora_37/home:Ximi1970:Mozilla:Add-ons.repo
