### ISSUE TITLE
SysTray-X is incompatible with Thunderbird 102.6.1

### ISSUE THREAD

**Issue by sean1985zc** [Ximi1970/systray-x#143]
No longer working on windows "SysTray-X is incompatible with Thunderbird 102.6.1"   

could it be updated?

**Comment by giwrgosmant** [comment]
> No longer working on windows "SysTray-X is incompatible with Thunderbird 102.6.1"
> 
> could it be updated?

In Windows 11 still working fine for me. I am currently on Thunderbird 102.7.
