### ISSUE TITLE
Autostart systray-x on Manjaro

### ISSUE THREAD

**Issue by kanishknishar** [Ximi1970/systray-x#144]
I am running Manjaro KDE and installed systray via ``yay -S systray-x-git``

I would like for Thunderbird to start up when my system boots minimized as a system tray icon.

**Comment by Ximi1970** [comment]
Create a bash script called thunderbird.sh like this:

```bash
#!/bin/bash
#
#
bash -c 'sleep 30; LC_TIME=en_GB.utf8 /usr/bin/thunderbird' &
```
and put it in your home dir. I needed the 30 sec delay for the Wifi to connect.
Then add a file named "thunderbird.sh.desktop" into the ~/.config/autostart directory containing this:

```
[Desktop Entry]
Exec=/home/<user>/thunderbird.sh
Icon=dialog-scripts
Name=thunderbird.sh
Path=
Type=Application
X-KDE-AutostartScript=true
```
change <user> into your used username.

**Comment by Ximi1970** [comment]
I forgot to mention the autostart of KDE is a bit broken since they use systemd,,,,

https://old.reddit.com/r/archlinux/comments/ves6mh/kde_autostart_mostly_no_longer_working/inf2mwq/

```
kwriteconfig5 --file startkderc --group General --key systemdBoot false
```

to get the old working system back.

**Comment by Ximi1970** [comment]
And check the "Start application minimized" in the preferences. Please be aware the minimize will only be done when Thunderbird is fully started and the add-ons are activated. Thunderbird itself has no option to start minimized.
Maybe you can try  the special window / application settings from KDE (right click top left icon, more actions)
to get it minimized earlier. Never tried.
