### ISSUE TITLE
Fedora 38 support and auto start fails

### ISSUE THREAD

**Issue by mi16087** [Ximi1970/systray-x#146]
When system starts, and thunderbird auto starts, it's all black and there is no thunderbird icon in tray. But when you close it and start thunderbird again (manually) it starts normaly with the icon showing in the tray. It's like extension is not activated when thunderbird autostart at system startup.
It all started after I updated to Fedora 38.

-Fedora 38 (64 bit)
-Gnome 44
-Thunderbird 102.10.0 (64 bit)
-systray-x 0.9.2
-I followed ReadMe for installation for fedora (adding repo, than instaling via dnf gnome version)

I also use "AppIndicator and KStatusNotifierItem Support" gnome extension

**Comment by Ximi1970** [comment]
Try version 0.9.4?

**Comment by mi16087** [comment]
i switched from fedora to nobara a month ago and everything works normally since then

**Comment by Ximi1970** [comment]
Fixed the rpm for fedora, but I have not release a new version yet.
The old installation method did not work anymore. Fedora always used a different way to add a system wide addon for thunderbird.
Now it is the same as the other distros.
