### ISSUE TITLE
Several thunderbird windows opened on startup

### ISSUE THREAD

**Issue by jdev082** [Ximi1970/systray-x#149]
**Describe the bug**
On startup, systray-x opens wayyy too many thunderbird windows (ranging from 2 to 16)

**To Reproduce**
install systray-x and have it autostart

**Expected behavior**
Only one instance of thunderbird starts up

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Architecture: 64 Bit
 - Desktop type / Window Manager: KDE 5.27.6, X11
 - Thunderbird Version and Arch:  (Tb 115.0.1, 64 bit)
 - Run `echo $XDG_SESSION_TYPE` in a terminal and report the results: `x11`
 - Extension Version: 0.9.4
 - App version: 0.9.4-1
 - Install type: systray-x-kde from Arch Linux x64 extra-testing 
 - Default system repository QT6

**Comment by jdev082** [comment]
One of the windows always closes the rest of the windows when closed. This is random. When any of the other windows are closed it closes the individual window.

**Comment by jdev082** [comment]
Now it's getting to the point where it opens so many instances of Thunderbird that it's crashing the system and using 100% CPU.

**Comment by Ximi1970** [comment]
Tested it with a clean VM of Arch with KDE.
Using my own repo: everything works just fine.
Using the Arch repo itself, everything works just fine.

Do not use the testing repo?

And what do you mean by auto start SysTray-X ??
The addon is started by Thunderbird itself. Systray-X itself will not launch Thunderbird in anyway.

**Comment by jdev082** [comment]
> Tested it with a clean VM of Arch with KDE. Using my own repo: everything works just fine. Using the Arch repo itself, everything works just fine.
> 
> Do not use the testing repo?
> 
> And what do you mean by auto start SysTray-X ?? The addon is started by Thunderbird itself. Systray-X itself will not launch Thunderbird in anyway.

I have Thunderbird added to autostart through KDE System Settings.

**Comment by jdev082** [comment]
Disabling the testing repos and downgrading the packages to stable does not fix the issue.
Removing it from autostart and starting manually does not solve the issue either.

**Comment by Ximi1970** [comment]
Are you aware that the default setting of KDE is to save your desktop when logging out. So if Thunderbird is open and you logout, you get on your next login the thunderbird KDE saved for you AND the autostart Thunderbird.
With every new login and open windows this amount doubles.....

So remove thunderbird from the autostart and just use the desktop save session of KDE.
Or use the autostart and use the manual save session of KDE.

**Comment by jdev082** [comment]
Occurs even with session saving completely disabled. Also occurs without systray-x even installed. Occurs no matter how the program is executed. It's opening so many windows that Google is rate limiting me.

**Comment by jdev082** [comment]
Found this: https://support.mozilla.org/en-US/questions/1201878
If I hadn't been blaming it on systray-x the whole time I would of found this solution faster
