### ISSUE TITLE
Since release 0.9.4, systray-x on Windows 11 doesn't work.

### ISSUE THREAD

**Issue by giwrgosmant** [Ximi1970/systray-x#153]
**Describe the bug**
I've already reported it [here](https://github.com/Ximi1970/systray-x/issues/147#issuecomment-1647743070), but seems for other platforms the app works. However in Windows 11 it doesn't work properly and so I open this ticket specific for Windows.
I mean the installation works ok now, (the path changed to C:\Program Files instead of User/AppData tho) and the extension appears in Thunderbird to enable it.
However, upon enable it doesn't work at all, no icon on tray and you can't close the window of Thunderbird with (X) only to minimize it with the minimize button.
The only version that works ok for now is 0.9.3 with the workaround you wrote [here](https://github.com/Ximi1970/systray-x/issues/147#issuecomment-1637063867).

**To Reproduce**
1. Remove the previous version of systray-x addon from Thunderbird.
2. Close Thunderbird.
3. Uninstall and remove previous version of the app. (Search also if any remained folder exist and delete it)
4. Install new version of the app, open Thunderbird and enable the addon.
5. There is no tray icon and you can't close the Thunderbird (X).

**Expected behavior**
It should have icon in the tray and the Thunderbird app to be able to close (minimize) it with X button.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Architecture: 64 bit
 - Thunderbird version and arch: 115.1.0 (64-bit)
 - Add-on version: 0.9.4 + 0.9.5
 - App version: 0.9.4 + 0.9.5

**Comment by Ximi1970** [comment]
Did you install the correct version of SysTray-X? You are using TB 64bit and you need to install the 64bit version of SysTray-X.
If you install the 32bit version it will only work with TB 32bit. TB 64bit will show the addon but will not start the companion app and the close button will do nothing.
The 64bit version of SysTray-X will work with both TB 32bit and 64bit.

**Comment by Ximi1970** [comment]
Ah wait, I also found a bug in 0.9.5....
If you closed TB using the systray icon menu when minimized, TB would still be running in the background. If you start TB again the companion app will be gone and the addon will not work anymore.
You can quit TB again with the TB menu.
the next time you start TB the addon works again and the companion app is also started again showing the systray icon.

**Comment by Ximi1970** [comment]
Thank you for the video. Looks like the companion app is just not started by TB.
Are there any error messages in the TB debug console?
Or maybe in the Windows Event Viewer?
Could you post the output also?

Tools -> Developer Tools -> "Click Ok on the hidden incoming connection dialog" -> Tab "Console"
(Do not know the Greek translations for these...)

Please feel free to remove the items that are private.

I will install the Greek version of Windows 11 en try to remember my ancient Greek lessons again :-) (or use the Translate app on my phone, maybe easier after so many years...)
Maybe something breaks in the communication between TB and the companion app when using the Greek character set....

**Comment by Ximi1970** [comment]
Read your mail and there is the culprit :-) There is still an old registry entry of SysTray-X due to a bug in the old 0.9.3 installer.
You need to manually remove the registry entry with regedit.exe.
BE CAREFULL USING THE REG EDITOR.

Find:
HKEY_CURRENT_USER\Software\Mozilla\NativeMessagingHosts\SysTray_X

And delete only the SysTray_X key from the NativeMessagingHosts key.

You can now install the new version.
