### ISSUE TITLE
[SECURITY] What is the purpose of the outbound connections?

### ISSUE THREAD

**Issue by Entrepreneur-AJ** [Ximi1970/systray-x#156]
**Describe the bug**
On a fresh install, I was configuring my firewall and noticed that your program is calling an external service. Is there a specific reason for this?

**To Reproduce**
Check outbound connections on firewall

**Expected behavior**
systray-x shouldn't be calling and external service. (unless I'm missing something important.)

**Screenshots**
![Systray-X-Outbound-Connectino](https://github.com/Ximi1970/systray-x/assets/118213587/9b4d7f35-a55e-4bbb-98d5-521061d55fc9)

**Desktop (please complete the following information):**
 - OS: Fedora 38 (linux)
 - Architecture: x86_64
 - Desktop type / Window Manager: KDE
 - Thunderbird version and arch TB 102.13.0 X64
 - Run `echo $XDG_SESSION_TYPE` in a terminal and report the results: X11
 - Add-on version: 0.9.5
 - App version: 0.9.5-70.1
 - Install type: rpm repo
 - Used Qt library whichever your  repo compiles with.

**Additional context**

**Comment by Ximi1970** [comment]
That is strange. The QT network module is not even loaded. And there is no code to make network connections. There is no need for it. You could check it yourself, it is all here on github :-)
Communications between TB and SysTray-X is a stdin/out pipe.

Will also check it in my VM Fedora 38 and other systems.

**Comment by Entrepreneur-AJ** [comment]
Okay, doing some more digging, looks like it's thunderbird doing the external calls, but something in your script is overriding the process showing on the firewall, thus why I thought it was your application calling out.
Happy to close the issue now, unless you want to keep it open to find out why the process name of systray-x is being used instead of thunderbird?
