### ISSUE TITLE
[Debian 10 - KDE] Thunderbird 115.3.1 - Systray is One Time Running

### ISSUE THREAD

**Issue by Feindfluglp** [Ximi1970/systray-x#158]
On Thunderbird 115.3.1 is Systray one time running and than its buggy.

Start Thunbird its running and after hide and show its buggy.
can´t after this not more hide in the taskbar.

**Desktop (please complete the following information):**
 - OS: Debian 10
 - Architecture: 64 Bit
 - Desktop type / Window Manager: KDE
 - Thunderbird version and arch: 115.3.1 64 Bit
 - Run `echo $XDG_SESSION_TYPE` ..: X11
 - Add-on version: 0.9.5
 - App version: 0.9.5
 - Install type: github repository build
 - Used Qt library: default system repository

**Comment by Feindfluglp** [comment]
OK. Every now and then it happens more often, but then it goes crazy again and can no longer be hidden.

**Comment by Ximi1970** [comment]
Did some experimenting without even systray-x installed...
Looks like Debian 10 broke Thunderbird somehow.
If you minimize Thunderbird and then logout KDE (with auto save session on) you will not be able to maximize TB again when you login again.
Only way to get it working again is to close TB using the taskbar by right clicking and selecting "close".
Start it again from the menu and it is working again.
Also tried it with the prebuild packages from the Thunderbird ftp site. Tried the 102.15.1 and the newest 115.3.2.
Some strange behavior when minimized, logout and login again. 
Debian 11 and 12 are working just fine.....
Maybe time to upgrade?

**Comment by Feindfluglp** [comment]
Interesting. But I won't upgrade my Debian for now. I'm satisfied and so far I don't have any other problems with the system. Is it possible for you to find out where the problem is? because it works, but only for a short time and then it goes crazy

**Comment by Ximi1970** [comment]
Please have a look at #159 
This seems to work with Debian 10

**Comment by Ximi1970** [comment]
Firefox will also crash when saved minimized.....

**Comment by Feindfluglp** [comment]
ok. i test the workaround in the next day, thank you for your nice work :)

**Comment by Feindfluglp** [comment]
I tested it and the error still persists. The first time he hides it and then continues to screw around

**Comment by Feindfluglp** [comment]
just a note. If I go to the addon settings in Thunderbird, deactivate systray and activate it again I can hide it again. sometimes it only works once or several times before it goes crazy again.

**Comment by Ximi1970** [comment]
Can you  post  any (error) output from:

Tools -> Developer Tools -> "Click Ok on the hidden incomming connection dialog" -> Tab "Console"

Please remove the items that are private.

**Comment by Feindfluglp** [comment]
sry, i have installed a old thunderbird (102.11.0) and its running.
can you tell me where the logs are? then I would send them to you.

**Comment by Ximi1970** [comment]
For TB 102 it is:

"Menu -> Tools -> Developer Tools -> Debug addons -> Find Systray-x in the window -> Click "Inspect" -> Select "Console" tab.
Mark and copy the output to the clipboard, kate or any other editor.

and:

"Menu -> Tools -> Developer Tools -> Error Console
Mark and copy the output to the clipboard, kate or any other editor.

**Comment by Feindfluglp** [comment]
Starting SysTray-X background.js:1001:9
Info Addon version: 0.9.5 background.js:16:13
Info Platform: {"os":"linux","arch":"x86-64"} background.js:17:13
Info Browser: {"name":"Thunderbird","vendor":"","version":"115.3.1","buildID":"20230928194049","majorVersion":"115","minorVersion":"3"} background.js:18:13
Using local storage 9 defaults.js:9:13

WebExtensions: windowEvent API started windowEvent.js:5
WebExtensions: Element 'titlebar-close' not found. Command not replaced. windowEvent.js:166
WebExtensions: Close listener added

Using local storage defaults.js:9:13
Stored filters: undefined or empty defaults.js:222:15
Force new filters: [{"accountId":"account1","version":"0.9.5","folders":["/INBOX"]},{"accountId":"account3","version":"0.9.5","folders":["/INBOX"]},{"accountId":"account4","version":"0.9.5","folders":["/INBOX"]}] defaults.js:259:15
Using local storage defaults.js:9:13
NotFoundError: No such JSWindowActor 'DevToolsFrame' 5
uncaught exception: Object

**Comment by Feindfluglp** [comment]
is whit the thunderbird 115.3.1 the same in the report :)

**Comment by Ximi1970** [comment]
Thanks!
But I cannot see any major error. The titlebar error is a remnant of the original "FireTray" addon. Still need to remove it.

Have you ever used any of the KDE "special" window / windows manager options you can find by right clicking on the titlebar icon on the leftside? (Right click -> More actions -> Configure special Windows / Application settings ?

**Comment by Feindfluglp** [comment]
I don't know exactly where you mean. Sounds to me like I never set anything there. but can't find what you mean.

**Comment by Ximi1970** [comment]
![image](https://github.com/Ximi1970/systray-x/assets/859953/1e681473-318a-42b1-84fb-a24d4f2a376b)

With the options found in these menus you can also manipulate the thunderbird windows. But this will interfere with the workings of systray-x.

**Comment by Ximi1970** [comment]
And hopefully you are not using any flatpak or snap package for TB....

**Comment by Ximi1970** [comment]
Please try to run the 'ldd' command in the directory where the SysTray-X binary resides and post the output.

```bash
more ~/.mozilla/native-messaging-hosts/SysTray_X.json
```
```bash
cd <path mentioned in the json without the last 'SysTray-X'>
ldd SysTray-X
```

**Comment by Feindfluglp** [comment]
i use the native paket from debia, not flatpak and its only install native.

ldd SysTray-X:
linux-vdso.so.1 (0x00007ffdb8570000)
        libX11.so.6 => /lib/x86_64-linux-gnu/libX11.so.6 (0x00007fa678f03000)
        libKF5Notifications.so.5 => /lib/x86_64-linux-gnu/libKF5Notifications.so.5 (0x00007fa678ea5000)
        libQt5Widgets.so.5 => /lib/x86_64-linux-gnu/libQt5Widgets.so.5 (0x00007fa67884e000)
        libQt5Gui.so.5 => /lib/x86_64-linux-gnu/libQt5Gui.so.5 (0x00007fa6782c3000)
        libQt5DBus.so.5 => /lib/x86_64-linux-gnu/libQt5DBus.so.5 (0x00007fa67822c000)
        libQt5Core.so.5 => /lib/x86_64-linux-gnu/libQt5Core.so.5 (0x00007fa677d2f000)
        libGL.so.1 => /lib/x86_64-linux-gnu/libGL.so.1 (0x00007fa677c99000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fa677c78000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fa677af4000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa677971000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fa677957000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa677797000)
        libxcb.so.1 => /lib/x86_64-linux-gnu/libxcb.so.1 (0x00007fa67776b000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fa677766000)
        libKF5CoreAddons.so.5 => /lib/x86_64-linux-gnu/libKF5CoreAddons.so.5 (0x00007fa6776c8000)
        libKF5ConfigCore.so.5 => /lib/x86_64-linux-gnu/libKF5ConfigCore.so.5 (0x00007fa677661000)
        libKF5WindowSystem.so.5 => /lib/x86_64-linux-gnu/libKF5WindowSystem.so.5 (0x00007fa677612000)
        libKF5Codecs.so.5 => /lib/x86_64-linux-gnu/libKF5Codecs.so.5 (0x00007fa6775d6000)
        libQt5TextToSpeech.so.5 => /lib/x86_64-linux-gnu/libQt5TextToSpeech.so.5 (0x00007fa6775c3000)
        libQt5X11Extras.so.5 => /lib/x86_64-linux-gnu/libQt5X11Extras.so.5 (0x00007fa6775bc000)
        libdbusmenu-qt5.so.2 => /lib/x86_64-linux-gnu/libdbusmenu-qt5.so.2 (0x00007fa67738b000)
        libphonon4qt5.so.4 => /lib/x86_64-linux-gnu/libphonon4qt5.so.4 (0x00007fa677305000)
        libpng16.so.16 => /lib/x86_64-linux-gnu/libpng16.so.16 (0x00007fa6772cc000)
        libharfbuzz.so.0 => /lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007fa6771d1000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fa6771b1000)
        libdbus-1.so.3 => /lib/x86_64-linux-gnu/libdbus-1.so.3 (0x00007fa67715e000)
        libicui18n.so.63 => /lib/x86_64-linux-gnu/libicui18n.so.63 (0x00007fa676e83000)
        libicuuc.so.63 => /lib/x86_64-linux-gnu/libicuuc.so.63 (0x00007fa676cb4000)
        libpcre2-16.so.0 => /lib/x86_64-linux-gnu/libpcre2-16.so.0 (0x00007fa676c39000)
        libdouble-conversion.so.1 => /lib/x86_64-linux-gnu/libdouble-conversion.so.1 (0x00007fa676c22000)
        libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007fa676b00000)
/lib64/ld-linux-x86-64.so.2 (0x00007fa6790ff000)
        libGLX.so.0 => /lib/x86_64-linux-gnu/libGLX.so.0 (0x00007fa676acc000)
        libGLdispatch.so.0 => /lib/x86_64-linux-gnu/libGLdispatch.so.0 (0x00007fa676a0f000)
        libXau.so.6 => /lib/x86_64-linux-gnu/libXau.so.6 (0x00007fa67680b000)
        libXdmcp.so.6 => /lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007fa676605000)
        libfam.so.0 => /lib/x86_64-linux-gnu/libfam.so.0 (0x00007fa6765f8000)
        libxcb-keysyms.so.1 => /lib/x86_64-linux-gnu/libxcb-keysyms.so.1 (0x00007fa6763f5000)
        libpulse.so.0 => /lib/x86_64-linux-gnu/libpulse.so.0 (0x00007fa6763a1000)
        libpulse-mainloop-glib.so.0 => /lib/x86_64-linux-gnu/libpulse-mainloop-glib.so.0 (0x00007fa67639b000)
        libfreetype.so.6 => /lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007fa6762df000)
        libgraphite2.so.3 => /lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007fa6762b0000)
        libsystemd.so.0 => /lib/x86_64-linux-gnu/libsystemd.so.0 (0x00007fa67620f000)
        libicudata.so.63 => /lib/x86_64-linux-gnu/libicudata.so.63 (0x00007fa67481f000)
        libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007fa6747ab000)
        libXext.so.6 => /lib/x86_64-linux-gnu/libXext.so.6 (0x00007fa674599000)
        libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007fa67457d000)
        libpulsecommon-12.2.so => /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-12.2.so (0x00007fa6744f7000)
        libcap.so.2 => /lib/x86_64-linux-gnu/libcap.so.2 (0x00007fa6744ef000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fa6744e5000)
        liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007fa6744bd000)
        liblz4.so.1 => /lib/x86_64-linux-gnu/liblz4.so.1 (0x00007fa67449c000)
        libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007fa67437e000)
        libX11-xcb.so.1 => /lib/x86_64-linux-gnu/libX11-xcb.so.1 (0x00007fa674379000)
        libICE.so.6 => /lib/x86_64-linux-gnu/libICE.so.6 (0x00007fa67415c000)
        libSM.so.6 => /lib/x86_64-linux-gnu/libSM.so.6 (0x00007fa674151000)
        libXtst.so.6 => /lib/x86_64-linux-gnu/libXtst.so.6 (0x00007fa673f4b000)
        libwrap.so.0 => /lib/x86_64-linux-gnu/libwrap.so.0 (0x00007fa673f3d000)
        libsndfile.so.1 => /lib/x86_64-linux-gnu/libsndfile.so.1 (0x00007fa673ec1000)
        libasyncns.so.0 => /lib/x86_64-linux-gnu/libasyncns.so.0 (0x00007fa673cbb000)
        libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007fa673c98000)
        libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007fa673c8f000)
        libXi.so.6 => /lib/x86_64-linux-gnu/libXi.so.6 (0x00007fa673a7d000)
        libnsl.so.1 => /lib/x86_64-linux-gnu/libnsl.so.1 (0x00007fa673a64000)
        libFLAC.so.8 => /lib/x86_64-linux-gnu/libFLAC.so.8 (0x00007fa6739f9000)
        libogg.so.0 => /lib/x86_64-linux-gnu/libogg.so.0 (0x00007fa6737f0000)
        libvorbis.so.0 => /lib/x86_64-linux-gnu/libvorbis.so.0 (0x00007fa6737c2000)
        libvorbisenc.so.2 => /lib/x86_64-linux-gnu/libvorbisenc.so.2 (0x00007fa673717000)
        libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007fa6736fb000)

**Comment by Feindfluglp** [comment]
I've never been in the window/application settings. I don't even know the window

**Comment by Feindfluglp** [comment]
hmm, did you find the problem? found a solution?

**Comment by Ximi1970** [comment]
No, because I cannot even replicate your problem. And I cannot see any problems in the outputs.
Maybe there is an library / app / plugin / setting you are using that causes the problem.

You could try the repository package but you really need to clean up the local build results first.
So remove the addon from the TB "Add-ons and Themes", remove the file in: ~/.mozilla/native-messaging-hosts/SysTray_X.json. And restart TB afterwards and double check the addon is removed.

**Comment by Feindfluglp** [comment]
so i have install the new systray 0.9.6 and this is in console:

sendRemoveListener on closed conduit systray-x@Ximi1970.549755813888 [ConduitsChild.sys.mjs:108](resource://gre/modules/ConduitsChild.sys.mjs)
    _send resource://gre/modules/ConduitsChild.sys.mjs:108
    removeListener resource://gre/modules/ExtensionChild.sys.mjs:675
    removeListener resource://gre/modules/ExtensionChild.sys.mjs:940
    register chrome://extensions/content/child/ext-storage.js:175
    removeListener resource://gre/modules/ExtensionCommon.sys.mjs:2869
    revoke resource://gre/modules/ExtensionCommon.sys.mjs:2891
    close resource://gre/modules/ExtensionCommon.sys.mjs:2896
    unload resource://gre/modules/ExtensionCommon.sys.mjs:979
    unload resource://gre/modules/ExtensionPageChild.sys.mjs:282
    unload resource://gre/modules/ExtensionPageChild.sys.mjs:319
    destroyExtensionContext resource://gre/modules/ExtensionPageChild.sys.mjs:479
    observe resource://gre/modules/ExtensionPageChild.sys.mjs:388

Starting SysTray-X [background.js:1070:9](moz-extension://e8edf2d5-5135-4cf9-b622-6d727587edd5/background.js)
Info Addon version: 0.9.6 [background.js:19:13](moz-extension://e8edf2d5-5135-4cf9-b622-6d727587edd5/background.js)
Info Platform: {"os":"linux","arch":"x86-64"} [background.js:20:13](moz-extension://e8edf2d5-5135-4cf9-b622-6d727587edd5/background.js)

Info Browser: {"name":"Thunderbird","vendor":"","version":"115.3.1","buildID":"20230928194049","majorVersion":"115","minorVersion":"3"} [background.js:21:13](moz-extension://e8edf2d5-5135-4cf9-b622-6d727587edd5/background.js)
Using local storage [defaults.js:5:13](moz-extension://e8edf2d5-5135-4cf9-b622-6d727587edd5/js/defaults.js)
Using local storage [defaults.js:5:13](moz-extension://e8edf2d5-5135-4cf9-b622-6d727587edd5/js/defaults.js)
Using local storage [defaults.js:5:13](moz-extension://e8edf2d5-5135-4cf9-b622-6d727587edd5/js/defaults.js)
Using local storage [defaults.js:5:13](moz-extension://e8edf2d5-5135-4cf9-b622-6d727587edd5/js/defaults.js)
Using local storage [defaults.js:5:13](moz-extension://e8edf2d5-5135-4cf9-b622-6d727587edd5/js/defaults.js)
Using local storage [defaults.js:5:13](moz-extension://e8edf2d5-5135-4cf9-b622-6d727587edd5/js/defaults.js)
WebExtensions: windowEvent API started [windowEvent.js:5](jar:file:///usr/lib/thunderbird/extensions/systray-x@Ximi1970.xpi!/js/windowEvent.js)

WebExtensions: Element 'titlebar-close' not found. Command not replaced. [windowEvent.js:166](jar:file:///usr/lib/thunderbird/extensions/systray-x@Ximi1970.xpi!/js/windowEvent.js)
WebExtensions: Close listener added [windowEvent.js:114](jar:file:///usr/lib/thunderbird/extensions/systray-x@Ximi1970.xpi!/js/windowEvent.js)
Using local storage [defaults.js:5:13](moz-extension://e8edf2d5-5135-4cf9-b622-6d727587edd5/js/defaults.js)
Using local storage [defaults.js:5:13](moz-extension://e8edf2d5-5135-4cf9-b622-6d727587edd5/js/defaults.js)
NotAllowedError: Could not open the file at /home/debian/.mozilla/native-messaging-hosts/SysTray_X.json [NativeMessaging.sys.mjs:115](resource://gre/modules/NativeMessaging.sys.mjs)
Using local storage [defaults.js:5:13](moz-extension://e8edf2d5-5135-4cf9-b622-6d727587edd5/js/defaults.js)
Using local storage

NotAllowedError: Could not open the file at /home/debian/.mozilla/native-messaging-hosts/SysTray_X.json [ExtensionCommon.sys.mjs:812](resource://gre/modules/ExtensionCommon.sys.mjs)
    normalizeError resource://gre/modules/ExtensionCommon.sys.mjs:812
    recvPortDisconnect resource://gre/modules/ExtensionChild.sys.mjs:292
    _recv resource://gre/modules/ConduitsChild.sys.mjs:77
    receiveMessage resource://gre/modules/ConduitsChild.sys.mjs:189
    (Async: JSActor query)
    _send resource://gre/modules/ConduitsChild.sys.mjs:59
    _send resource://gre/modules/ConduitsParent.sys.mjs:288
    promises resource://gre/modules/ConduitsParent.sys.mjs:328
    map self-hosted:221
    _cast resource://gre/modules/ConduitsParent.sys.mjs:328
    sendPortDisconnect resource://gre/modules/ExtensionParent.sys.mjs:414
    onConnect resource://gre/modules/NativeMessaging.sys.mjs:140
    handler resource://gre/modules/EventEmitter.sys.mjs:91
    emit resource://gre/modules/EventEmitter.sys.mjs:154
    _cleanup resource://gre/modules/NativeMessaging.sys.mjs:291
    startupPromise resource://gre/modules/NativeMessaging.sys.mjs:116
    (Async: promise callback)
    NativeApp resource://gre/modules/NativeMessaging.sys.mjs:113
    openNative resource://gre/modules/ExtensionParent.sys.mjs:276
    recvPortConnect resource://gre/modules/ExtensionParent.sys.mjs:362
    _recv resource://gre/modules/ConduitsChild.sys.mjs:77
    receiveMessage resource://gre/modules/ConduitsParent.sys.mjs:453
    (Async: JSActor query)
    _send resource://gre/modules/ConduitsChild.sys.mjs:59
    _send resource://gre/modules/ConduitsChild.sys.mjs:111
    connect resource://gre/modules/ExtensionChild.sys.mjs:368
    connectNative chrome://extensions/content/child/ext-runtime.js:77
    callFunction resource://gre/modules/ExtensionCommon.sys.mjs:1132
    callFunction resource://gre/modules/ExtensionChild.sys.mjs:728
    callAndLog resource://gre/modules/ExtensionChild.sys.mjs:708
    callFunction resource://gre/modules/ExtensionChild.sys.mjs:728
    stub resource://gre/modules/Schemas.sys.mjs:2920
    init moz-extension://e8edf2d5-5135-4cf9-b622-6d727587edd5/background.js:693
    start moz-extension://e8edf2d5-5135-4cf9-b622-6d727587edd5/background.js:1064
    InterpretGeneratorResume self-hosted:1455
    AsyncFunctionNext self-hosted:852
    (Async: async)
    <anonymous> moz-extension://e8edf2d5-5135-4cf9-b622-6d727587edd5/background.js:1073

Uncaught (in promise) Error: Attempt to postMessage on disconnected port
    postSysTrayXMessage moz-extension://e8edf2d5-5135-4cf9-b622-6d727587edd5/background.js:705
    sendPreferencesStorage moz-extension://e8edf2d5-5135-4cf9-b622-6d727587edd5/background.js:631
    promise callback*sendPreferences moz-extension://e8edf2d5-5135-4cf9-b622-6d727587edd5/background.js:589
    init moz-extension://e8edf2d5-5135-4cf9-b622-6d727587edd5/background.js:70
    start moz-extension://e8edf2d5-5135-4cf9-b622-6d727587edd5/background.js:1067
    async* moz-extension://e8edf2d5-5135-4cf9-b622-6d727587edd5/background.js:1073

[background.js:705:32](moz-extension://e8edf2d5-5135-4cf9-b622-6d727587edd5/background.js)
    sendPreferences moz-extension://e8edf2d5-5135-4cf9-b622-6d727587edd5/background.js:593
    AsyncFunctionThrow self-hosted:856
    (Async: async)
    init moz-extension://e8edf2d5-5135-4cf9-b622-6d727587edd5/background.js:70
    start moz-extension://e8edf2d5-5135-4cf9-b622-6d727587edd5/background.js:1067
    InterpretGeneratorResume self-hosted:1455
    AsyncFunctionNext self-hosted:852
    (Async: async)
    <anonymous> moz-extension://e8edf2d5-5135-4cf9-b622-6d727587edd5/background.js:1073

Uncaught (in promise) Error: Attempt to postMessage on disconnected port
    postSysTrayXMessage moz-extension://e8edf2d5-5135-4cf9-b622-6d727587edd5/background.js:705
    sendMailCount moz-extension://e8edf2d5-5135-4cf9-b622-6d727587edd5/js/defaults.js:502
    listenerFolderInfoChanged moz-extension://e8edf2d5-5135-4cf9-b622-6d727587edd5/background.js:328
    init moz-extension://e8edf2d5-5135-4cf9-b622-6d727587edd5/background.js:118
    start moz-extension://e8edf2d5-5135-4cf9-b622-6d727587edd5/background.js:1067
    async* moz-extension://e8edf2d5-5135-4cf9-b622-6d727587edd5/background.js:1073
background.js:705:32

Uncaught (in promise) Error: Attempt to postMessage on disconnected port
    postSysTrayXMessage moz-extension://e8edf2d5-5135-4cf9-b622-6d727587edd5/background.js:705
    focusChanged moz-extension://e8edf2d5-5135-4cf9-b622-6d727587edd5/background.js:935
    promise callback*focusChanged moz-extension://e8edf2d5-5135-4cf9-b622-6d727587edd5/background.js:934
    init moz-extension://e8edf2d5-5135-4cf9-b622-6d727587edd5/background.js:132
    start moz-extension://e8edf2d5-5135-4cf9-b622-6d727587edd5/background.js:1067
    async* moz-extension://e8edf2d5-5135-4cf9-b622-6d727587edd5/background.js:1073

**Comment by Feindfluglp** [comment]
and now I can do whatever I want, it's no longer hidden. Before, it sometimes worked and sometimes it didn't.

**Comment by Ximi1970** [comment]
If you restart TB do you have still have these errors?
Now it looks like there are two instances of SysTray-X running. The system one (working) and a local one for  user  'debian' not working and causing the errors.
But a not allowed error?? 

If there are still errors, please could you run:
```bash
ls -la /home/debian/.mozilla/native-messaging-hosts
```
```bash
ls -la /home/debian/.thunderbird
```
```bash
ls -la /home/debian/.thunderbird/*.default/extensions
```

and post the outputs?

**Comment by Feindfluglp** [comment]
so, i have all new installed and this is the output:
ls -la /home/debian/.mozilla/native-messaging-hosts:
- No files

ls -la /home/debian/.thunderbird
insgesamt 52
drwx------  6 debian debian  4096 Okt 29 16:15  .
drwxr-xr-x 92 debian debian 20480 Okt 29 16:15  ..
drwx------  3 debian debian  4096 Okt 29 16:15 'Crash Reports'
drwx------ 11 debian debian  4096 Okt 29 16:16  egr7frrs.default-default
-rw-r--r--  1 debian debian    62 Okt 29 16:15  installs.ini
drwx------  2 debian debian  4096 Okt 29 16:15  nx0ac2rn.default
drwx------  2 debian debian  4096 Okt 29 16:15 'Pending Pings'
-rw-r--r--  1 debian debian   259 Okt 29 16:15  profiles.ini

ls -la /home/debian/.thunderbird/*.default/extensions
- No files

and the developer console:
1698592704775	addons.xpi	WARN	Checking /usr/lib/thunderbird/distribution/extensions for addons
Found 0 public keys and 0 secret keys (0 protected, 0 unprotected) [RNPLib.jsm:551:15](chrome://openpgp/content/modules/RNPLib.jsm)

services.settings: Failed to load last_modified.json: TypeError: NetworkError when attempting to fetch resource. [Utils.sys.mjs:322](resource://services-settings/Utils.sys.mjs)
1698592705955	addons.xpi	WARN	Addon with ID thunderbird-compact-light@mozilla.org already installed, older version will be disabled
1698592705955	addons.xpi	WARN	Addon with ID thunderbird-compact-dark@mozilla.org already installed, older version will be disabled
Starting SysTray-X [background.js:1070:9](moz-extension://54d022f7-d70e-42f8-99d6-53d5822dae65/background.js)
Info Addon version: 0.9.6 [background.js:19:13](moz-extension://54d022f7-d70e-42f8-99d6-53d5822dae65/background.js)
Info Platform: {"os":"linux","arch":"x86-64"} [background.js:20:13](moz-extension://54d022f7-d70e-42f8-99d6-53d5822dae65/background.js)

Info Browser: {"name":"Thunderbird","vendor":"","version":"115.4.1","buildID":"20231024181440","majorVersion":"115","minorVersion":"4"} [background.js:21:13](moz-extension://54d022f7-d70e-42f8-99d6-53d5822dae65/background.js)
Using local storage 10 [defaults.js:5:13](moz-extension://54d022f7-d70e-42f8-99d6-53d5822dae65/js/defaults.js)
WebExtensions: windowEvent API started [windowEvent.js:5](jar:file:///usr/lib/thunderbird/extensions/systray-x@Ximi1970.xpi!/js/windowEvent.js)
WebExtensions: Element 'titlebar-close' not found. Command not replaced. [windowEvent.js:166](jar:file:///usr/lib/thunderbird/extensions/systray-x@Ximi1970.xpi!/js/windowEvent.js)
WebExtensions: Close listener added [windowEvent.js:114](jar:file:///usr/lib/thunderbird/extensions/systray-x@Ximi1970.xpi!/js/windowEvent.js)

File closed [NativeMessaging.sys.mjs:218](resource://gre/modules/NativeMessaging.sys.mjs)
    writePromise resource://gre/modules/NativeMessaging.sys.mjs:218
Accounts: [] [background.js:100:13](moz-extension://54d022f7-d70e-42f8-99d6-53d5822dae65/background.js)
Using local storage [defaults.js:5:13](moz-extension://54d022f7-d70e-42f8-99d6-53d5822dae65/js/defaults.js)
Stored filters: undefined or empty [defaults.js:217:15](moz-extension://54d022f7-d70e-42f8-99d6-53d5822dae65/js/defaults.js)

Force new filters: [] [defaults.js:238:15](moz-extension://54d022f7-d70e-42f8-99d6-53d5822dae65/js/defaults.js)
Using local storage [defaults.js:5:13](moz-extension://54d022f7-d70e-42f8-99d6-53d5822dae65/js/defaults.js)
Uncaught (in promise) Error: Attempt to postMessage on disconnected port
    postSysTrayXMessage moz-extension://54d022f7-d70e-42f8-99d6-53d5822dae65/background.js:705
    sendMailCount moz-extension://54d022f7-d70e-42f8-99d6-53d5822dae65/js/defaults.js:502
    listenerFolderInfoChanged moz-extension://54d022f7-d70e-42f8-99d6-53d5822dae65/background.js:328
    init moz-extension://54d022f7-d70e-42f8-99d6-53d5822dae65/background.js:118

[background.js:705:32](moz-extension://54d022f7-d70e-42f8-99d6-53d5822dae65/background.js)
Uncaught (in promise) Error: Attempt to postMessage on disconnected port
    postSysTrayXMessage moz-extension://54d022f7-d70e-42f8-99d6-53d5822dae65/background.js:705
    focusChanged moz-extension://54d022f7-d70e-42f8-99d6-53d5822dae65/background.js:935
[background.js:705:32](moz-extension://54d022f7-d70e-42f8-99d6-53d5822dae65/background.js)

**Comment by Feindfluglp** [comment]
and its a new thunderbird 115.4.1

**Comment by Ximi1970** [comment]
Looks like the addon is not started for some reason. That generates the postMessage error.
What happens if you run: 
```bash
SysTray-X
```
do you get any response or does it just return without any message as it should?

Did you enable any extra security options for your system (like apparmor) or have you extra security tools running that would prevent an app launching another app?
Are you using other Thunderbird plugins or add-ons?

Debugging a system remotely by slow chat is not easy....

**Comment by Feindfluglp** [comment]
SysTray-X 
- No response

I didn't make any other settings, no other security software, nothing. So nothing that would prevent systray-x from starting.
If I do the whole thing with Thunderbird 102, it works.
I think it depends on the Thunderbird version.

I don't use any other Thunderbird addons, just systray-x.

**Comment by Ximi1970** [comment]
I am just amazed by your problems. What ever I do in my default Debian 10 KDE virtual machine, it works just perfectly fine, no strange things.

You could try is this:
Create a new user on your system, login as that user and start Thunderbird.
Setup a new test mail account and look if SysTray-X works better with the new user.

You could also try to reset the SysTray-X preference storage in the addon preferences but I really cannot imaging how a bad storage could cause this strange behavior.

**Comment by Feindfluglp** [comment]
So, I have now deleted everything again or uninstalled it with purge.
once restarted everything reinstalled and now it runs with the new thunderbird and systray-x 0.9.6 and hides again and can get it again.
There are no more errors in the developer console.

I would like to thank you very much for your help :)

**Comment by Feindfluglp** [comment]
for me is the thread closed
