### ISSUE TITLE
No tray icon on "Fedora 31"

### ISSUE THREAD

**Issue by knobsam** [Ximi1970/systray-x#16]
Hello,

first thanks for your work!

I followed the README and built the add-on locally.
After starting TB it is minimized, but there is no tray icon visible.

I'm using Gnome 3.34.5 on Fedora 31 right now.
Do you have any ideas what went wrong maybe or how I can fix that?

Best regards,

Samuel

**Comment by loveless90** [comment]
Have you [KStatusNotifierItem/AppIndicator Support](https://extensions.gnome.org/extension/615/appindicator-support/) installed manually or was installed automatically or by you via the package management system? If that's the case, you can try the steps of #13.

**Comment by knobsam** [comment]
Hi,

I've installed it manually yesterday after reading your comment. I also reinstalled the XPI via Thunderbird, but still no icon (minimize to taskbar works).

About the companion app, how exactly should this app being started? Is Thunderbird/the AddOn taking care of this?

**Comment by Ximi1970** [comment]
Sorry not compatible yet due to wayland. Working on it!

**Comment by knobsam** [comment]
Oh Ok. Then I will wait patiently for the fix/implementation.

**Comment by Ximi1970** [comment]
The icon can needs to be enabled by hand for now (already fixed my test package) on Fedora. 
```bash
sudo install gnome-shell-extension-appindicator
gnome-extensions enable appindicatorsupport@rgcjonas.gmail.com
```
Logout and in again. The icon should be visible now if TB is started with addon.
Another problem is now the missing number of unread mails on Fedora.

**Comment by Ximi1970** [comment]
Looks like Fedora has a badly compiled Thunderbird package, joy...
If you install the binary Thunderbird 68.6.0 from Mozilla it works just fine.

**Comment by Ximi1970** [comment]
@knobsam should be fixed in develop branch. But only if you use the mozilla thunderbird binary. I do not know what Fedora did with their version of TB...

**Comment by Ximi1970** [comment]
Please try the new version 0.1.5. But you still need to download the Mozilla version to get it working. Fedora killed the Webextension API in some way.
