### ISSUE TITLE
README.md fix for KNotifications in Build instructions

### ISSUE THREAD

**Issue by mjeveritt** [Ximi1970/systray-x#160]
Re: https://github.com/Ximi1970/systray-x#building :

I found in Ubuntu 20.04.6 LTS I had to install `libkf5notifications-dev` to avoid `Project ERROR: Unknown module(s) in QT: "KNotifications"` occurring when I build for KDE.

I didn't need to bother with `gnome-extensions enable ubuntu-appindicator@ubuntu.com` as I didn't have `gnome-shell` installed, and I doubt I need it for my KDE builds!

**Comment by Ximi1970** [comment]
Updated the README build instructions
