### ISSUE TITLE
Arch PKGBUILD needs dependencies updates

### ISSUE THREAD

**Issue by ItachiSan** [Ximi1970/systray-x#162]
**Describe the bug**
The packages at:
https://build.opensuse.org/package/show/home:Ximi1970:Mozilla:Add-ons/systray-x
are not built due to the fact that recently the `knotifications` package has been renamed to `knotifications5`.

**To Reproduce**
Either:
- Check the *Arch* build at the above link
- Install the package
- Update existing packages, when one update is `knotifications`

For example, reinstalling the package has the following output:
```console
$ sudo pacman -S systray-x
[sudo] password for giovanni: 
warning: systray-x-1:0.9.5-0 is up to date -- reinstalling
resolving dependencies...
warning: cannot resolve "knotifications", a dependency of "systray-x"
:: The following package cannot be upgraded due to unresolvable dependencies:
      systray-x

:: Do you want to skip the above package for this upgrade? [y/N] 
error: failed to prepare transaction (could not satisfy dependencies)
:: unable to satisfy dependency 'knotifications' required by systray-x
```

**Expected behavior**
I am able to install / upgrade systray-x and other packages.

**Screenshots**
See the console log above.

**Desktop (please complete the following information):**
 - OS: ArchLinux
 - Architecture (32 or 64 bit): 64bit
 - Desktop type / Window Manager (KDE, Xfce, Cinnamon, MATE etc): Plasma
 - Thunderbird version and arch (Tb xx.xx.x, 32 or 64 bit): 115.3.3
 - Thunderbird package type (repository, mozilla binary, flatpak, snap, etc): repository
 - Run `echo $XDG_SESSION_TYPE` in a terminal and report the results: wayland
 - Add-on version: 0.9.5
 - App version: 0.9.5
 - Install type: github repository build, script installer, OBS repository: OBS repository
 - Used Qt library (default system repository, other OBS repo, self-compiled, Qt online installer): default repo

**Additional context**
None for now. Additional information can be provided.

**Comment by Ximi1970** [comment]
Yup already in the test :-)

**Comment by Ximi1970** [comment]
https://github.com/Ximi1970/systray-x/commit/9656829a45021b7f0b502f873e9f3f74f5cc9f1e
