### ISSUE TITLE
Window doesnt got to fullscreen after klicking on icon

### ISSUE THREAD

**Issue by Ralosso** [Ximi1970/systray-x#163]
The Window doesnt go back to fullscreen after minimizing to system tray and clicking the Icon. 
It opens full and then shrinking 1cm on each side. 
"normal" minimizing is working and the window goes back to fullscreen.

Linux Mint 21.2 XFCE 64
TB 115.3.1 64-Bit from upstream 
X11
github repo
default system repository

thanks for your work on this thing :3

**Comment by Ximi1970** [comment]
New release and packages generated.
