### ISSUE TITLE
restore issue for dual monitors

### ISSUE THREAD

**Issue by duguyipiao** [Ximi1970/systray-x#165]
The latest commit 60e5f6cd5cdee1a8d48997e77d38f6dfd30c0a29 breaks the restore for dual monitors. The thunderbird window is always restored to the primary monitor, even if it was in the secondary monitor before minimizing to tray.

Tested on xfce 4.18 with thunderbird 115.

**Comment by Ximi1970** [comment]
Cannot test every thing :-) Fixed.
