### ISSUE TITLE
Unread message count not displayed in tray icon

### ISSUE THREAD

**Issue by katonagl** [Ximi1970/systray-x#168]
**Describe the bug**
The number of unread messages is not displayed, although it is set in preferences and folders are selected. The behavior does not change with API count method turned on or off.

**Desktop (please complete the following information):**
 - OS: openSUSE Tumbleweed
 - Architecture: 64bit
 - Desktop type / Window Manager: KDE
 - Thunderbird version and arch (Tb xx.xx.x, 32 or 64 bit): 115.5.1 (64 bit)
 - Thunderbird package type (repository, mozilla binary, flatpak, snap, etc): openSUSE Tumbleweed repository
 - Run `echo $XDG_SESSION_TYPE` in a terminal and report the results: x11
 - Add-on version: 0.9.7-78.3 from Ximi1970 openSUSE repo
 - App version: 0.7.0 build 710 from Ximi1970 openSUSE repo
 - Install type: OBS repository.  
 - Used Qt library: default system repository

**Additional context**
Downgrading to 0.9.5-3.1 from Ximi1970 openSUSE repo solves the problem

**Comment by Ximi1970** [comment]
You have got two different versions of SysTray-X running. Or did you made a typo?
Addon is 0.9.7 and the app is 0.7.0.
This will not work. Sometimes it does work a bit, but the interface changed a lot in the last version.
Please install only one version. Both the addon and app should report the same version.
But if you experimented with a github version, make sure to remove the SysTray_X.json in ~/.mozilla/native-messaging-hosts if the file exists. Probably a left over when trying a manually installed version.

**Comment by katonagl** [comment]
OMG, you are right. It is a more than 2 years old leftover. And it haven't caused any issues until now.
