### ISSUE TITLE
Betterbird support

### ISSUE THREAD

**Issue by mohamedhagag** [Ximi1970/systray-x#171]
Hi all,
this is not working with betterbird anymore as the companion app is looking for thunderbird specific version as I got from reading the code.

How can we change this to work with betterbird ?

Regards

_Originally posted by @mohamedhagag in https://github.com/Ximi1970/systray-x/issues/114#issuecomment-1899068208_

**Comment by Ximi1970** [comment]
Please fill in all the details when posting an issue. I trying to maintain 20+ systems....

I checked betterbird again and the addon is still working fine for betterbird on openSuSE Leap 15.5, binary download from betterbird.eu (115.3.2 and 115.6.1)

I extended the thunderbird check code with betterbird 3 months ago.

**Comment by mohamedhagag** [comment]
Ok it's working in build 0.9.8 but not 0.9.5
Thanks alot for the great effort .

Regards,

> Please fill in all the details when posting an issue. I am trying to maintain 20+ systems....
> 
> I checked betterbird again and the addon is still working fine for betterbird on openSuSE Leap 15.5, binary download from betterbird.eu (115.3.2 and 115.6.1)
> 
> I extended the thunderbird check code with betterbird 3 months ago.
