### ISSUE TITLE
How to do not autostart

### ISSUE THREAD

**Issue by niels0n** [Ximi1970/systray-x#172]
Hey there, I'm trying to use systray-x on kde, but when I login it automatically opens a thunderbird instance and I don't like that.
I saw that I can start it minimized (although it actually start maximized, and then it's minimized automatically after like one second), but isn't there a way to not autostart thunderbird nor systray-x at all and just having systray-x appearing when, and if, opening thunderbird?

**Comment by Ximi1970** [comment]
First of all systray-x does not start TB. TB always starts the addons / plugins.
So the addons / plugins can only start doing things as soon as TB is fully started and there will always be a delay.
TB cannot start minimized. The option "start minimize/in tray" the plugin provides is more an automatic minimize when TB is started.

If KDE starts a TB, remove it from the session before quitting/logging out if you use automatic session save.
Second option, use a manually saved session without TB.
Third option:
If you really want TB to start minimized, please use the KDE special window/applications settings, top right app icon, right click, more options, configure special....

**Comment by niels0n** [comment]
I'm sorry, you're right. I had my session settings messed up.
Now it works perfectly. Thank you!
