### ISSUE TITLE
Does not work on Gentoo

### ISSUE THREAD

**Issue by asarubbo** [Ximi1970/systray-x#18]
Hi, first thanks for your effort.

Being Gentoo a rolling distro, is not simply to reproduce the issue because of the different versions. However, atm, I have:
- xorg-1.20.7
- kde-plasma 5.17.5

I compiled it manually and I copied the extension over .thunderbird/*.default/extensions directory.
I also started SysTray-X but:

- by double-clicking on the icon, nothing happens
- by right-clicking on the icon and then "Show/Hide" nothing happens
- the counter does not work as well

Is there something else I can provide to debug the issue?

**Comment by Ximi1970** [comment]
Added to the list!

**Comment by Ximi1970** [comment]
If you know where to get a recent KDE Gentoo image for the Virtualbox that would be great. Tried a "shortcut" install that took 12 hours but ended up with nothing usefull. Joy...

**Comment by loveless90** [comment]
Did you test this: [https://www.osboxes.org/gentoo/#gentoo-201910-vbox](https://www.osboxes.org/gentoo/#gentoo-201910-vbox)?

**Comment by Ximi1970** [comment]
Yes I did. And tried again. Does not want to be updated to the latest version. and I am now willing to dive into the pages and pages of manuals....

**Comment by Ximi1970** [comment]
Looks like I found the magic button...

**Comment by Ximi1970** [comment]
Should be working now. Please try the new 0.1.5 version.
