### ISSUE TITLE
Reset mail count when Thunderbird Window has been shown

### ISSUE THREAD

**Issue by tbertels** [Ximi1970/systray-x#183]
**Is your feature request related to a problem? Please describe.**
When not using the API count method (which slows down Thunderbird on my system), we have to open a different folder then go back to inbox to update the new mail count.

**Describe the solution you'd like**
Reset the mail count once Thunderbird has been shown aka restored (which means we've checked the new mail).

**Describe alternatives you've considered**

**Additional context**

**Comment by Ximi1970** [comment]
I found a bug preventing the app from clearing the new mail icon. It now follows the new mail indication like TB. As long as there is a new mail marker in the TB folder, the new mail icon stays "active".

**Comment by Ximi1970** [comment]
New release.
