### ISSUE TITLE
Failed installation with error: libqt5core5t64 (>= 5.15.1) but it is not installable

### ISSUE THREAD

**Issue by adamwebber2** [Ximi1970/systray-x#189]
Getting this error after trying to install the package systray-x on debian-12

The following packages have unmet dependencies:
 systray-x : Depends: ccccccccccccccccccccccc
             Depends: libqt5gui5t64 (>= 5.11.0~rc1) but it is not installable or
                      libqt5gui5-gles (>= 5.11.0~rc1) but it is not going to be installed
             Depends: libqt5widgets5t64 (>= 5.15.1) but it is not installable
             Depends: libstdc++6 (>= 13.1) but 12.2.0-14 is to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by adamwebber2** [comment]
Networking issue with qubes

**Comment by adamwebber2** [comment]
Closed

**Comment by Ximi1970** [comment]
Install and works just fine on my clean Debian 12 Gnome / KDE.

If you want to file a bug report, please use the standard form and fill in the details of your system / distro:

https://github.com/Ximi1970/systray-x/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=
