### ISSUE TITLE
New mail indicator does not show anymore in the system tray icon

### ISSUE THREAD

**Issue by antoyo** [Ximi1970/systray-x#190]
**Describe the bug**
The system tray icon (at least on Linux), does not show the indicator that there's a new mail.

**To Reproduce**

 * Receive a new mail.

**Expected behavior**
The new mail indicator should show that there's a new mail.

**Desktop (please complete the following information):**
 - OS / distribution: ArchLinux
 - Architecture (32 or 64 bit): 64 bits
 - Desktop type / Window Manager (KDE, Xfce, Cinnamon, MATE etc): i3 window manager
 - Thunderbird version and arch (Tb xx.xx.x, 32 or 64 bit): Thunderbird 115.10.2, 64 bits
 - Thunderbird package type (repository, mozilla binary, flatpak, snap, etc): ArchLinux repository
 - Run `echo $XDG_SESSION_TYPE` in a terminal and report the results: x11
 - Add-on version: 0.9.9
 - App version: (I don't know what this is)
 - Install type: Archlinux repository.
 - Used Qt library: default system repository

**Additional context**
The debug window shows:
```
Unread mail: 0
New mail: 0
```
so it seems like it never detects the new mails.

**Comment by katonagl** [comment]
I have the same bug, have to downgrade to previous version to make it work again.

**Comment by Ximi1970** [comment]
Workaround is to select the API count method.

**Comment by katonagl** [comment]
It only works for me if new mail indicator is checked. Otherwise the number of unread mail is never displayed. And even with the new mail indicator selected there is a lag of ca. 5 seconds until the tray icon changes. I go back to previous version now, that works perfectly.

**Comment by Ximi1970** [comment]
I cannot reproduce it anymore with the latest arch and newly build package. Glad I am not using Arch....(and never will)

**Comment by Nikolai5** [comment]
Bit unnecessary, but thanks appreciate your effort.

**Comment by RoblKyogre** [comment]
unsure if necessary, but i had been experiencing this bug even with the latest thunderbird (115.12.2) and systray-x (0.9.9).
ended up fixing this issue by just renaming my `.thunderbird` folder to something else and having thunderbird recreate it, so i'm assuming some setting somewhere got messed up and caused this to happen.

here's system info, as well as what i tried before just renaming the folder:
> Like the original issue, I'm using Arch Linux (x86_64) and have both thunderbird and systray-x installed from the arch repos, but in contrast, I'm using KDE Plasma and am on Wayland instead. Neither the custom icon nor mail indicator workarounds worked for me, and the debug window shows 0 unread or new mail, despite having the API Count option enabled and having all my inboxes selected under "mail" in systray-x settings.

**Comment by Ximi1970** [comment]
Found a bug in the "old" new mail detection. Fixed it but it is not in a release yet.

**Comment by Ximi1970** [comment]
New release.
