### ISSUE TITLE
[Windows] Unfortunately incompatible with Thundebird 128

### ISSUE THREAD

**Issue by momonix** [Ximi1970/systray-x#191]
**Is your feature request related to a problem? Please describe.**
Thunderbird 115 autoupdated to 128 (Windows)... systray-x is disabled (incompatible with the TB version).
I've disabled the Thunderbird Linux updates.

**Describe the solution you'd like**
Update systray-x

**Describe alternatives you've considered**
None. Systray-x is unique!... and terribly useful!

**Additional context**
Thanks for your work. Much appreciated.

**Comment by Ximi1970** [comment]
Forgot to generate the updated 0.9.9 windows version...
I will upload it as soon as it passes my small test.

But please be aware that there seems to be a problem with TB 128.0 according to the website of [Betterbird](https://www.betterbird.eu/)

**Comment by Ximi1970** [comment]
Packages are now available in the release assets for 0.9.9:
SysTray-X-setup32-0.9.9-2.exe 
SysTray-X-setup64-0.9.9-2.exe

**Comment by momonix** [comment]
Thanks a lot!
