### ISSUE TITLE
thunderbird-beta

### ISSUE THREAD

**Issue by Cherkah** [Ximi1970/systray-x#194]
**Is your feature request related to a problem? Please describe.**
i'm using thunderbird-beta (V. 130) on archlinux which is not recognized by systray-x.
 
**Describe the solution you'd like**
I wish systray-x could also support thunderbird-beta
 
**Describe alternatives you've considered**
even if thunderbird-beta version 130 brings the icon in the systray, the feature of reduction in the systray + notification of unread is still not implemented.
so no alternative is currently available to systray-x

**Additional context**

I saw the systray-x 's code and doesn't looks like a lot of work is needed to insert thunderbird-beta.
maybe i'am wrong

**Comment by Ximi1970** [comment]
Was just creating a new release. Updated the TB version also. Be aware that I do not test TB betas really good. I normally only check if the addon will minimize and maximize. Still need to look if there are any errors in de console.

**Comment by Cherkah** [comment]
woa really cool
ok i gonna to wait for it & hop it will strike soon

**Comment by Ximi1970** [comment]
Sorry, I am not going to add beta releases to the package. There are to many bugs and unexpected changes in every new "release" of the betas / alphas.

If you really want to live on the edge and risk scrambling all your mail, install the standard thunderbird version and systray-x first, then manually add the add-on in the latest TB 130 beta by using the "install add-on from file" option in the "Add-ons and themes" dialog of TB.
You can find the XPI here:
```
/usr/lib/thunderbird/distribution/extensions/systray-x@Ximi1970.xpi
```
This will only work for the TB 130.xxx betas but only if they do not change to much.
As soon as they move to TB 131, this will not work anymore. You need to update the TB version in the manifest json and compile the git repository yourself.
