### ISSUE TITLE
systray-x incompatible with TB 128

### ISSUE THREAD

**Issue by christophehenry** [Ximi1970/systray-x#198]
**Describe the bug**
The extension has ben deactivated in TB here since update to 128.2.0esr.

**Desktop (please complete the following information):**
 - OS / distribution: Fedora 40 - Architecture (32 or 64 bit)
 - Desktop type / Window Manager: KDE (plasma 6)
 - Thunderbird version and arch (Tb xx.xx.x, 32 or 64 bit): 128.2.0esr (64 bits)
 - Thunderbird package type (repository, mozilla binary, flatpak, snap, etc): openSuSE repository
 - Run `echo $XDG_SESSION_TYPE` in a terminal and report the results: X11
 - Add-on version: 0.9.3
 - App version: 0.9.3
 - Install type: openSuSE repository  
 - Used Qt library: default system

**Comment by Ximi1970** [comment]
Please update to the latest version 0.9.10.

**Comment by christophehenry** [comment]
Ok, that's weird… IDK why the addon was still in version 0.9.3 event though the package itself was correctly updated to 0.9.10. I had to reinstall but eventually, everything worked. Thk for your help!

**Comment by Cherkah** [comment]
i post hier because i don't want to open an issue which is similar to this one.

systray-x doesnt work well with tbunderbird 128:
all categories in "windows" section setting are unresponsiveness

is it "normal" due to the fact that this Version is buggy and you do not want to get touche on it or that is from my side?
regards and thanks again for this app!

     OS / distribution: endeavouros (arch)
    Desktop type / Window Manager: KDE (plasma 6.1.5)
    Thunderbird 128
    App version: 0.9.10-1
    Used Qt library: 6.7.2

**Comment by Ximi1970** [comment]
Tested it  again in the latest arch with TB 128.2.0esr.  I cannot not see any problems.
I would recommend to update your system.

**Comment by Cherkah** [comment]
i'm asking my self if it is not an issue with apparmor or sysctl stuff.conf !?
im gonna to investigate.

regards
