### ISSUE TITLE
Windows 10: cannot unhide Thunderbird from tray

### ISSUE THREAD

**Issue by id-acc** [Ximi1970/systray-x#20]
Thunderbird 68.7.0
SysTray-X 0.1.4
Windows 10 uses the "Use small taskbar buttons" setting.
SysTray-X uses the "Minimize to tray" setting. 
Thunderbird is hided to tray.
"Show" does not completly restore Thunderbird from tray. A window appeared, but Thunderbird is missing from the taskbar. Clicking on a Thunderbird window, affects the window behind Thunderbird.

**Comment by Ximi1970** [comment]
Sorry, could not replicate your problem maybe I already tackled that problem. Please try the new version 0.1.5.

**Comment by id-acc** [comment]
Sorry, this is may be my mistake. Thunderbird 32bit and SysTray-X 64bit.
Thunderbird 68.8.0 64bit and SysTray-X 0.15 64bit it's OK
