### ISSUE TITLE
New emails in folder are not counted when it has sub-folders

### ISSUE THREAD

**Issue by mpamps** [Ximi1970/systray-x#21]
I have a folder "A" with two sub-folders "B" and "C".
- A
 -- B
 -- C

I have all 3 folders to be checked for new emails, but only emails in folders B and C are counted.
Emails in folder A are not counted.

This only occurs when a folder has sub-folders.

----------
OS: Linux Mint 19.3 Tricia (base: Ubuntu 18.04 LTS) - 64bit
Dekstop: Cinnamon
Thunderbird: 68.7.0 (64-bit)
SysTray-X: 0.1.5
Installation type: 18.04LTS repo
Qt: 5.9.5 (default system repo)

**Comment by Ximi1970** [comment]
Oops. thank you for reporting.

**Comment by Ximi1970** [comment]
Solved in the develop branch. Will automatically be available in a next release.

**Comment by mpamps** [comment]
I just updated systray-x today to version 0.2.0 (via Mint "Update Manager").
Is this issue solved in this version?
I saw a new option in the folders section: "^ Add base folder".
I checked it but no luck.

**Comment by Ximi1970** [comment]
Oops, got mangled in the new experimental API. It is again on top of the todo.

**Comment by Ximi1970** [comment]
Fixed again for the new api

**Comment by Ximi1970** [comment]
Fixed it again. Please checkout 0.2.1.

**Comment by mpamps** [comment]
Works great! Thanks!
