### ISSUE TITLE
New mail number indicator font too small

### ISSUE THREAD

**Issue by PutinVladimir** [Ximi1970/systray-x#22]
Please add settings to choose font (size).

**Comment by zcalusic** [comment]
Agree... the number seems quite small and unreadable currently.

If not too much to ask, what I remember from FireTray days, the font size would actually automatically adjust, depending on the count of unread emails. So, in the case of only several email unread (<10, single digit), it was full size and quite readable. Then, as the number increased (tens, hundreds...), the digits got smaller to fit the small available area in the tray. I remember it working very well and I liked it a lot. :+1: 

Please consider... and thanks a lot for your work, Systray-X is indispensable.

**Comment by fabianski7** [comment]
Which distro and DE are you using?
For me, this latest version is not showing the new email icon. I believe that the systray-x is not detecting the new messages.

Operating System: Arch Linux 
KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.70.0
Qt Version: 5.14.2
Kernel Version: 5.6.13-arch1-1
OS Type: 64-bit
OS and architecture used: archlinux 5.6.3 64-bit
Thunderbird: 68.6.0
Add-on version: 0.2.0
Used Qt library: default system repository
