### ISSUE TITLE
Possibility to choose a custom icon

### ISSUE THREAD

**Issue by fabianski7** [Ximi1970/systray-x#25]
If that were not possible, perhaps it would be ideal to have an icon with another color.
Something like this: https://svgur.com/s/LMz https://svgshare.com/s/LLc https://svgur.com/s/LM0

**Comment by Ximi1970** [comment]
It is already possible in the preferences: Custom icon

**Comment by fabianski7** [comment]
this one 
![160604-21-05-2020](https://user-images.githubusercontent.com/47755037/82596033-2b2d2500-9b96-11ea-84e4-08c694999651.png)

**Comment by Ximi1970** [comment]
Oh oke. Another option on the list.

**Comment by fabianski7** [comment]
Thank you 💚
