### ISSUE TITLE
KDE session start SysTray-X binary directly

### ISSUE THREAD

**Issue by PutinVladimir** [Ximi1970/systray-x#26]
If save session with running TB. Then relogin you will see two icon in tray. One starting by TB and working and second SysTray-X starting directly by session manager and not working(even exit) so need kill process.
I don't know is it possible to fix in the app or not.
For now I manually edited session file but I use manual session saving if somebody use automatic session saving with each logout this is not an option.

**Comment by Ximi1970** [comment]
I cannot do much about the session management but I can build in a check to verify it is started by TB and if not exit immediately.

**Comment by Ximi1970** [comment]
Please have a look at the 0.2.1 release. Should be solved.
