### ISSUE TITLE
Can we implement "Close to tray"?

### ISSUE THREAD

**Issue by sean1985zc** [Ximi1970/systray-x#27]

**Comment by Ximi1970** [comment]
Already in the latest release

**Comment by sean1985zc** [comment]
I am using KDE Neon (based on ubuntu 18.04) and installed systray-x Release test 0.2.1, but closing to tray is not happening and there's no option in the tray menu?

**Comment by Ximi1970** [comment]
In preferences, under Windows, check minimize to tray method 1, and check minimize on close.

**Comment by sean1985zc** [comment]
![Screenshot_20200527_111800](https://user-images.githubusercontent.com/3360312/83007635-dcefaa00-a00b-11ea-93d9-516f0087f859.png)

**Comment by sean1985zc** [comment]
I am not able to find "check minimize on close"

**Comment by Ximi1970** [comment]
Then you do not have the latest version. Check the about. Should say version 0.2.1

**Comment by sean1985zc** [comment]
works perfectly for now, thanks
