### ISSUE TITLE
Number size don't save

### ISSUE THREAD

**Issue by PutinVladimir** [Ximi1970/systray-x#29]
It is reset to 10 after restart TB.

**Comment by PutinVladimir** [comment]
More info:
1. Setting changed thru TB plugin and "save" button there is keept value between restarts TB.
2. Clicking "Ok" in preferences of companion window is reset "Number size" to 10.
3. Minimize always resets to "Minimize to tray, mothod 1" (in both plugin and companion) and don't understand what option do...

**Comment by Ximi1970** [comment]
Included in 0.4.0
