### ISSUE TITLE
openSUSE / KDE package fixes 

### ISSUE THREAD

**Issue by askembris** [Ximi1970/systray-x#3]
I am copying this from https://github.com/Ximi1970/FireTray/issues/47#issuecomment-587213428 for easier tracking. 

These are various issues I encountered with the systray-x-0~git20200210.8e4aeb5-13.1.x86_64.rpm package:

a) The tray icon appeared. Yay!
b) I have two IMAP accounts (both from Google). The number of unread emails only appears if I have unread messages in the second account. If I deactivate it from the preferences, no number is shown (even when there is unread e-mail in the first account).
c) The message count is always 1, regardless of how many unread messages there are in the mailbox.
d) Clicking on the icon minimises the window to the task bar (like clicking on the minimise button). It should close the window and remove it from the taskbar while running in the background, I guess.
e) Closing the window exits the program (and the tray icon disappears), where it should keep running in the background.
f) At a couple of points I lost the tray icon (I supposed something crashed), but I am not sure what transpired to reproduce it consistently.

I think it's a great start and you should keep up the good work!

**Comment by Ximi1970** [comment]
Please add the OpenSuSE version. If you are using Tumbleweed also add the architecture (32 or 64 bit). And also the Thunderbird version would be helpfull.  
Thank you.

**Comment by askembris** [comment]
> Please add the OpenSuSE version. If you are using Tumbleweed also add the architecture (32 or 64 bit). And also the Thunderbird version would be helpfull.
> Thank you.

I am using 64bit Tumbleweed, and the testing was conducted using Thunderbird 68.5.

**Comment by Ximi1970** [comment]
Point e) cannot be solved right now. I have no control anymore over the close sequence of TB with the new APIs. There is a small chance intercepting the close by embedding the TB window but the first experiment are not very nice and have a lot of side effects.

Could you please test it again for the other problems with the new release version? Thanks!
If the count still freezes please choose a longer poll startup / interval time in de settings.

**Comment by Ximi1970** [comment]
Please try the new release 0.1.5.
