### ISSUE TITLE
0.3.0 does not start minimized

### ISSUE THREAD

**Issue by lgbaldoni** [Ximi1970/systray-x#30]
Using rpm from home:Ximi1970:Mozilla:Add-ons/systray-x on Leap 15.1 and KDE.

**Comment by Ximi1970** [comment]
Using the default TB of  15.1, I can not replicate your problem using the same repo. Did you select in preferences the "Start application minimized" option and clicked "Ok"/"Save"?

I did a logout and login an Tb started minimized. Also from the command line it starts miniminized.

**Comment by lgbaldoni** [comment]
This is my configuration:
![systray_cfg](https://user-images.githubusercontent.com/1450716/84591934-7c9d9c80-ae42-11ea-97e0-04da0e29bcd5.jpg)

I tried to log out and to launch from the command line, but neither made a difference.
How could I debug this? Or perhaps I should test 15.2 ?

**Comment by Ximi1970** [comment]
Preferences look fine. Just a bit amazed you need to set 16 for number size.

It works just fine for me (clean, updated 15.1 with default KDE and TB). Did you ever experiment  with the special window settings for TB that can be found under the TB icon on the title bar
(More actions-> Special window or special application settings)
to override default window behavior?
Or do you have another tool running to manipulate window behavior?

The minimize on start is an internal TB javascript function that just should work standalone (even if the SysTray-X Qt app is not starting for whatever reason)
For that function not to work, you need to have a non standard TB startup I have not encountered yet. (default is the "3pane" Mail view (left the accounts, top right mail headers, bottom right empty/selected mail)

You can always try 15.2 of course.

**Comment by lgbaldoni** [comment]
Update: I tried plain 15.2 with a fresh profile and everything worked.
I then migrated my profile and the problem came up again. It appears to be related to the [folder account](https://addons.thunderbird.net/it/thunderbird/addon/folder-account/) extension.

Also I've noticed that the application does not restart minimised in any case: is this to be expected?

**Comment by Ximi1970** [comment]
Ah thank you for investigating further. I will have a look at that add-on and hopefully find out what is happening in this case.

**Comment by Ximi1970** [comment]
> Also I've noticed that the application does not restart minimised in any case: is this to be expected?

You need to be more specific. It is working in your first line of your comment and then it is never working in the last line??

To be hopefully clear:

If the start minimized option is checked, the addon will try to minimize TB as soon as possible.   

Keep in mind that I do not have (yet?) a direct API to the minimize function of TB, so there will always be a delay in the minimizing.
This can sometimes cause TB to startup normally on startup and as soon as the addon is started by TB the addon will minimize the window.  

See also the FAQ.txt

**Comment by lgbaldoni** [comment]
> You need to be more specific. It is working in your first line of your comment and then it is never working in the last line??

Even when start minimised works, if I e.g. disable an extension and click on the internal restart link, thunderbird won't be minimised. I have to quit and start manually if I want that.

**Comment by Ximi1970** [comment]
I do not have many plugins running. Only enigmail, exquilla, lighting, manual sort folders, systray-x and the old (incompatible/disabled) firetray.
With these everything is running just fine. I will have a look at the folder account add-on you mentioned.

Do you have any other add-ons installed?

**Comment by lgbaldoni** [comment]
CompactHeader, Folder Account, Lightning, Manually sort folders, Systray-X and likewise the old firetray (disabled).

**Comment by Ximi1970** [comment]
I think this is a problem how TB is handling legacy plugins (like exquilla and folder-account) and web extension plugins (like systray-x). Found a solution to force a minimize by the addon app. Strangely enough the problem is only when starting TB from the menu or command line. If it is started due to a session login everything seems fine.  
So TB will start normally now but is minimized by the addon app as soon as it is started. So TB is shortly not minimized. You will see it "flashing" by.  
Be aware that as soon TB 78 is released, all legacy plugins will not work anymore (and the problem should be solved).
So no more folder-account, exquilla etc....  

Currently only in the feature-multiwin branch.  Hopefully I have time to clean and test the branch next few days en make a new release.

**Comment by Ximi1970** [comment]
Included in 0.4.0
