### ISSUE TITLE
No way to close multiple windows when 'Minimize on close' is enabled

### ISSUE THREAD

**Issue by andreymal** [Ximi1970/systray-x#32]
Thunderbird allows to open multiple windows, but if the 'Minimize on close' option is enabled, they are always minimized when I try to close them, and I didn't find a way to close extra windows, so this option is non-usable.

I think it would be good to check windows count if possible: if there is only one window, then minimize, otherwise close until only one window remains.

OS / Architecture: any
Thunderbird: 68
SysTray-X: Release test 0.3.0 (github build)

**Comment by Ximi1970** [comment]
If you use minimize on close you can always close the window from the file menu "Close". "Quit" will close and quit all windows.  

For now I have implemented to "minimize" all windows when pressing "Close". I did not find a way to ID the window of the one the close button is pressed, so I cannot do a "special" action for that window from the app side. Still looking for a way around that problem.

**Comment by Ximi1970** [comment]
Included in 0.4.0
