### ISSUE TITLE
Install in CentOs 7

### ISSUE THREAD

**Issue by Yarrax** [Ximi1970/systray-x#36]
CentOs7 doesn't have gnome-shell-extension-appindicator in repos.

Also i can't make for KDE:

Creating systray-x@Ximi1970.xpi
Creating systray-x app
Info: creating stash file /home/agp/systray-x/app/build/.qmake.stash
Project MESSAGE: Buildnumber: 431
Project MESSAGE: Git hash: 8b702f529c7b4fc5d6809e676be864333ed0e9fe
Project MESSAGE: Git branch: develop
Project MESSAGE: Version: 0.3.0
Project ERROR: Unknown module(s) in QT: KNotifications
make[1]: Вход в каталог `/home/agp/systray-x/app/build'
make[1]: *** Не заданы цели и не найден make-файл.  Останов.
make[1]: Выход из каталога `/home/agp/systray-x/app/build'
cp: не удалось выполнить stat для «app/build/SysTray-X»: Нет такого файла или каталога
make: *** [systray-x-app] Ошибка 1

But build for Gnome work in KDE4 very well.

**Comment by Ximi1970** [comment]
If you want to compile the package your self with all KDE options, please install:  
sudo yum install epel-release
sudo yum install kf5-knotifcations

Or use:
make OPTIONS="DEFINES+=NO_KDE_INTEGRATION"

**Comment by Ximi1970** [comment]
CentOS has been added in 0.6.1
