### ISSUE TITLE
Systray-X doesn't work when two user accounts are logged.

### ISSUE THREAD

**Issue by tmorard** [Ximi1970/systray-x#38]
On a computer, with two user accounts, Systray-X works correctly on the first account opened but crashes on the second account opened if the other account is logged. There is no need to launch Thunderbird on the first one, just open account and Systray-X doesn't work for the second user.

Example : 
first : UserA open (works), second : UserB open (fails)
first : UserB open (works), second : UserA open (fails)
first : UserA open (works), second : UserA close, third : UserB open (works)

Specs : 
OS : Linux Mint 20 MATE
Windows manager : MATE
Thunderbird : 68.10.0 (64 bits) - default system repository
Systray-X version : 0.3.0 - OBS repository

**Comment by Ximi1970** [comment]
How do you use the second account? Do you use the switch user option? I can see there is an error in that case:

Invalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 key...

when the second user tries to start SysTray-X app.
I think this is more a desktop/X11 problem somehow. When trying to use vncserver it even crashes my desktop. Joy..
Atm I am using Leap 15.2 with KDE.
Will try to pinpoint the problem.
But it looks like de X-server is not happy sharing a dual desktop environment here.

**Comment by tmorard** [comment]
Yes, I use the switch user option to use the second account.
I open the first account and launch Thunderbird with Systray-X, I switch 
to the second user with "switch user" (Thunderbird and Systray-X are 
always opened on first account), I launch Thunderbird (with Systray-X) 
on the second account.
On the second account Systray-X crashs but Thunderbird, MATE desktop and 
other app work well.

I have this crash report from Mate desktop, I don't know if it can be 
usefull.


===================================================================
  Info
===================================================================
            PID: 10281 (SysTray-X)
            UID: 1001 (user2)
            GID: 1001 (user2)
         Signal: 11 (SEGV)
      Timestamp: Mon 2020-07-20 10:48:15 CEST (40s ago)
   Command Line: /usr/bin/SysTray-X 
/usr/lib/mozilla/native-messaging-hosts/SysTray_X.json systray-x@Ximi1970
     Executable: /usr/bin/SysTray-X
  Control Group: /user.slice/user-1001.slice/session-c7.scope
           Unit: session-c7.scope
          Slice: user-1001.slice
        Session: c7
      Owner UID: 1001 (user2)
        Boot ID: bd26c9a2da744cbdbdaa7064d8191335
     Machine ID: 2e6db7b3feeb408ba59f7482257bc249
       Hostname: DesktopPC
        Storage: 
/var/lib/systemd/coredump/core.SysTray-X.1001.bd26c9a2da744cbdbdaa7064d8191335.10281.1595234895000000000000.lz4
        Message: Process 10281 (SysTray-X) of user 1001 dumped core.

                 Stack trace of thread 10281:
                 #0  0x00007f1a615aa854 XDefaultRootWindow (libX11.so.6 
+ 0x2c854)
                 #1  0x0000561fd958468f n/a (SysTray-X + 0x2468f)
                 #2  0x0000561fd9582609 n/a (SysTray-X + 0x22609)
                 #3  0x0000561fd9575959 n/a (SysTray-X + 0x15959)
                 #4  0x0000561fd956d897 n/a (SysTray-X + 0xd897)
                 #5  0x00007f1a5ff800b3 __libc_start_main (libc.so.6 + 
0x270b3)
                 #6  0x0000561fd956dace n/a (SysTray-X + 0xdace)

                 Stack trace of thread 10282:
                 #0  0x00007f1a6006e96f __GI___poll (libc.so.6 + 0x11596f)
                 #1  0x00007f1a5ff3ac1a n/a (libxcb.so.1 + 0xbc1a)
                 #2  0x00007f1a5ff3c90a xcb_wait_for_event (libxcb.so.1 
+ 0xd90a)
                 #3  0x00007f1a5c8fd298 n/a (libQt5XcbQpa.so.5 + 0x78298)
                 #4  0x00007f1a604079d2 n/a (libQt5Core.so.5 + 0xbe9d2)
                 #5  0x00007f1a5fb43609 start_thread (libpthread.so.0 + 
0x9609)
                 #6  0x00007f1a6007b103 __clone (libc.so.6 + 0x122103)
===================================================================
  GDB Log
===================================================================
[New LWP 10281]
[New LWP 10282]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/bin/SysTray-X 
/usr/lib/mozilla/native-messaging-hosts/SysTray_X.json systr'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f1a615aa854 in XDefaultRootWindow () from 
/usr/lib/x86_64-linux-gnu/libX11.so.6
[Current thread is 1 (Thread 0x7f1a5d224800 (LWP 10281))]

===================================================================
  GDB Backtrace
===================================================================
[New LWP 10281]
[New LWP 10282]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/bin/SysTray-X 
/usr/lib/mozilla/native-messaging-hosts/SysTray_X.json systr'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f1a615aa854 in XDefaultRootWindow () from 
/usr/lib/x86_64-linux-gnu/libX11.so.6
[Current thread is 1 (Thread 0x7f1a5d224800 (LWP 10281))]
#0  0x00007f1a615aa854 in XDefaultRootWindow () from 
/usr/lib/x86_64-linux-gnu/libX11.so.6
#1  0x0000561fd958468f in ?? ()
#2  0x0000561fd9582609 in ?? ()
#3  0x0000561fd9575959 in ?? ()
#4  0x0000561fd956d897 in ?? ()
#5  0x00007f1a5ff800b3 in __libc_start_main (main=0x561fd956d840, 
argc=3, argv=0x7fff11bc2288, init=<optimized out>, fini=<optimized out>, 
rtld_fini=<optimized out>, stack_end=0x7fff11bc2278) at 
../csu/libc-start.c:308
#6  0x0000561fd956dace in ?? ()

===================================================================
  GDB Backtrace (all threads)
===================================================================
[New LWP 10281]
[New LWP 10282]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/bin/SysTray-X 
/usr/lib/mozilla/native-messaging-hosts/SysTray_X.json systr'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f1a615aa854 in XDefaultRootWindow () from 
/usr/lib/x86_64-linux-gnu/libX11.so.6
[Current thread is 1 (Thread 0x7f1a5d224800 (LWP 10281))]

Thread 2 (Thread 0x7f1a5c0f7700 (LWP 10282)):
#0  0x00007f1a6006e96f in __GI___poll (fds=0x7f1a5c0f6ca8, nfds=1, 
timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
         resultvar = 18446744073709551100
         sc_cancel_oldtype = 0
         sc_ret = <optimized out>
#1  0x00007f1a5ff3ac1a in ?? () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
No symbol table info available.
#2  0x00007f1a5ff3c90a in xcb_wait_for_event () from 
/usr/lib/x86_64-linux-gnu/libxcb.so.1
No symbol table info available.
#3  0x00007f1a5c8fd298 in ?? () from 
/usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
No symbol table info available.
#4  0x00007f1a604079d2 in ?? () from 
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#5  0x00007f1a5fb43609 in start_thread (arg=<optimized out>) at 
pthread_create.c:477
         ret = <optimized out>
         pd = <optimized out>
         unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139751190394624, 
992385512751409698, 140733490928414, 140733490928415, 140733490928608, 
139751190392576, -868894271711040990, -868888832917329374}, 
mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 
0x0, cleanup = 0x0, canceltype = 0}}}
         not_first_call = 0
#6  0x00007f1a6007b103 in clone () at 
../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 1 (Thread 0x7f1a5d224800 (LWP 10281)):
#0  0x00007f1a615aa854 in XDefaultRootWindow () from 
/usr/lib/x86_64-linux-gnu/libX11.so.6
No symbol table info available.
#1  0x0000561fd958468f in ?? ()
No symbol table info available.
#2  0x0000561fd9582609 in ?? ()
No symbol table info available.
#3  0x0000561fd9575959 in ?? ()
No symbol table info available.
#4  0x0000561fd956d897 in ?? ()
No symbol table info available.
#5  0x00007f1a5ff800b3 in __libc_start_main (main=0x561fd956d840, 
argc=3, argv=0x7fff11bc2288, init=<optimized out>, fini=<optimized out>, 
rtld_fini=<optimized out>, stack_end=0x7fff11bc2278) at 
../csu/libc-start.c:308
         self = <optimized out>
         result = <optimized out>
         unwind_buf = {cancel_jmp_buf = {{jmp_buf = {94694790441824, 
992385512751409698, 94694790322848, 140733490930304, 0, 0, 
-992047397418128862, -868888317884323294}, mask_was_saved = 0}}, priv = 
{pad = {0x0, 0x0, 0x3, 0x7fff11bc2288}, data = {prev = 0x0, cleanup = 
0x0, canceltype = 3}}}
         not_first_call = <optimized out>
#6  0x0000561fd956dace in ?? ()
No symbol table info available.
#0  0x00007f1a615aa854 in XDefaultRootWindow () from 
/usr/lib/x86_64-linux-gnu/libX11.so.6
#1  0x0000561fd958468f in ?? ()
#2  0x0000561fd9582609 in ?? ()
#3  0x0000561fd9575959 in ?? ()
#4  0x0000561fd956d897 in ?? ()
#5  0x00007f1a5ff800b3 in __libc_start_main (main=0x561fd956d840, 
argc=3, argv=0x7fff11bc2288, init=<optimized out>, fini=<optimized out>, 
rtld_fini=<optimized out>, stack_end=0x7fff11bc2278) at 
../csu/libc-start.c:308
#6  0x0000561fd956dace in ?? ()




Le 18/07/2020 à 13:31, Maxime Rijnders a écrit :

**Comment by Ximi1970** [comment]
Included in 0.4.0
