### ISSUE TITLE
INstructions not clear

### ISSUE THREAD

**Issue by d-packs** [Ximi1970/systray-x#39]
Nowhere in the user interface is it clear what the numbers in the polling interval represent. I can't find anything in the documentation either.

So is it seconds or minutes? It might be a good idea to display this information in the configuration UI.

![capture-200720-135028](https://user-images.githubusercontent.com/33980111/87930011-00752500-ca90-11ea-8e3b-9dbe7bab3eba.png)
![capture-200720-134955](https://user-images.githubusercontent.com/33980111/87930014-010dbb80-ca90-11ea-9a9e-a15afdf7dc95.png)

**Comment by Ximi1970** [comment]
You are using a really old systray-x version. Polling has been removed a few months ago. Was just a temporary solution till I found I decent way to get a listener service working with the new TB api. Please upgrade...
But if you really want to know:

Poll startup delay (in seconds): Is the time to wait until the plugin starts looking for new mail (needed to prevent polling before TB is ready with whatever it does on startup.
Poll interval (in seconds): How many seconds to wait before polling again for new mail. If to short CPU usage is 100% al the time.
