### ISSUE TITLE
How to report bugs.

### ISSUE THREAD

**Issue by Ximi1970** [Ximi1970/systray-x#4]
Please use the "Bug report" issue template. See the option after clicking "New issue".

Or  
start your bug report mentioning at least:

- OS and architecture used (32 or 64 bit)
- Desktop / Window Manager (KDE, Xfce, Cinnamon, MATE etc)
- Run `echo $XDG_SESSION_TYPE` in a terminal and report the results
- Thunderbird version and arch (32 or 64 bit)
- Add-on version (Tb -> Menu (-> Tools) -> Addons and Themes -> Extensions -> click SysTray-X)
- App version  (Right click icon -> About)
- Install type: How did you install: github repository build, script installer or OBS repository.
- Used Qt library (default system repository, other OBS repo, self-compiled, Qt online installer)

Bug description, how to reproduce, what you expect to happen.

Thank you for reporting!

**Comment by mjeveritt** [comment]
It should be possible to set up an Issue 'proforma' /template, as other projects have, within Github somewhere!
