### ISSUE TITLE
Folder settings are lost with restart

### ISSUE THREAD

**Issue by fdellwing** [Ximi1970/systray-x#40]
```
Version: 0.3.0 DEB
TB: 68.10.0 x64
Linux: Kubuntu 18.04 x64
```

The addon does only count new mails in the `Inbox` not every new mail in the account. Please change that behaviour as 99% of my mails will be sorted directly into folders.

![Screenshot_20200810_105136](https://user-images.githubusercontent.com/22813377/89766170-fe830c80-daf7-11ea-98a8-9ba322949ce4.png)

**Comment by Ximi1970** [comment]
Please have a look at the preferences of the plugin (tab "Mail" -> Accounts) and select all the folders you need to be checked. The default behavior is indeed to check the inbox only.

**Comment by fdellwing** [comment]
That is a bit unintuitive. Could you give us an "auto subscribe" function that we can enable for folders? Now if I create a new folder, I need to manually add it to the addon, although I already have the parent directory added.

**Comment by fdellwing** [comment]
I also found a real bug, the folder settings are lost after closing and reopening TB.

**Comment by Ximi1970** [comment]
Did you press the save button after you selected the folders?

**Comment by fdellwing** [comment]
Yes, otherwise it would not change to show the unread mails at all. But currently I have to do it every time I bootup the computer again.

**Comment by Ximi1970** [comment]
I am a bit confused on what Systray-X version your are using. You say 0.3.0 DEB. Are you using the script installer for debian 10 for Kubuntu? There is a special version for all Ubuntu versions called xUbuntu. There is also a repository you can use.

I also cannot reproduce the save problem you have. Did you previously try/use the older SysTray-X versions?

**Comment by fdellwing** [comment]
```
[07:48 root@mb-fade fade] > apt-cache policy systray-x
systray-x:
  Installiert:           0.3.0
  Installationskandidat: 0.3.0
  Versionstabelle:
 *** 0.3.0 500
        500 https://download.opensuse.org/repositories/home:/Ximi1970:/Mozilla:/Add-ons/xUbuntu_18.04 ./ Packages
        100 /var/lib/dpkg/status
```

And no, I just switched to TB 68 and therefore from FireTray to SysTray-X.

---

1. I have the following set:
    - Minimize to tray, method 1
    - Minimize on close
    - Default Thunderbird
    - KDE integration (Hide)
    - Custom Icon
    - Display unread message count
    - Black
    - 18
2. I have 2 Accounts in my TB, on the first I would like to subscribe all subfolders and on the second only the Inbox.
3. I set that and click save
4. Taskbar symbol with correct count shows
5. File -> Close
6. Reopen TB
7. Folder settings gone

**Comment by Ximi1970** [comment]
Oke, will update my Kubuntu image and check it again. And I am going to investigate if I can implement the automatic add of a newly created directory when the parent dir is selected.

**Comment by fdellwing** [comment]
I have recreated the issue with a blank Kubuntu 18.04 live-CD and made a snapshot from the thunderbird profile folder. If you contact me on Twitter, I can send you the things.

**Comment by Ximi1970** [comment]
https://github.com/Ximi1970/systray-x/issues/40#issuecomment-671744502 I have add the auto add feature but it is still not in develop or a release. Hopefully this week.  

Sorry no twitter for me, you can send a mail to: ximi.github@gmail.com
Thought the email address was already visible but it was not...Added it to my profile.
Thnx fir the info!

**Comment by katonagl** [comment]
I confirm this bug. After Tb restart only unread mail in Inbox is displayed regardless previously set folders.

System: Opensuse Tumbleweed
Thunderbird 78.5.1 (64 bit)
Systray-x 0.6.1

**Comment by fdellwing** [comment]
Problem is gone with TB78 for me.

**Comment by atomGit** [comment]
confirming settings lost on TB restart - i suspect possibly many of the reports of STX not working may be due to this

TB 78.12.0
STX 0.7.0
Manjaro Linux
