### ISSUE TITLE
Unread mail - Fontsize not working with custom symbol

### ISSUE THREAD

**Issue by fdellwing** [Ximi1970/systray-x#41]
Ok, this is a strange one and I'm kind of sure it worked at some point.

The font size does work for all icons but a custom one. Font color is working for everyone.

**Comment by fdellwing** [comment]
I saw that you use the icon size for some calculations (https://github.com/Ximi1970/systray-x/blob/c2262658399cd3c09b04c46996d48fa0f1abd1c9/app/SysTray-X/systrayxicon.cpp#L302), is it possible that this breaks somewhat if the icon has an abitrary size? I will check on my computer tomorrow, what size the icon is.

**Comment by fdellwing** [comment]
I tested that and can confirm my assumption.

My icon (png) is only 32x32 and the font size has no (visible) effect. If I switch to another icon (png, 512x512) it instantly changes the visible fontsize.

**Comment by Ximi1970** [comment]
Will try to find a better way to calculate the font size.

**Comment by Ximi1970** [comment]
Included in 0.4.0
