### ISSUE TITLE
Thunderbird 78 Support

### ISSUE THREAD

**Issue by kelebek333** [Ximi1970/systray-x#42]
Hi,

Could you add Thunderbird 78 support to xpi file. I edited /webext/manifest.json file and compile, so xpi/extension file working properly on Thunderbird 78.x.

`"strict_max_version": "78.*"`

**Comment by kelebek333** [comment]
Hi,

I installed systray-x from repository (Ubuntu focal base) to Linux Mint 20. Xpi version in the package does not support Thunderbird 78 version. But now I noticed that you added Thunderbird 79.x support to github. 

Could you update repositories.

Best regards.

**Comment by kelebek333** [comment]
I added fixed package for Thunderbird 78 to my PPA (supported xUbuntu 16.04, 18.04, 20.04 / Linux Mint 18.x, 19.x, 20.x). 

```
sudo add-apt-repository ppa:kelebek333/tools
sudo apt-get update
sudo apt install systray-x 
```

**Comment by Ximi1970** [comment]
Trying to pick all up again. Had very little time past months.

**Comment by zcalusic** [comment]
No apologies required, @Ximi1970, you're doing great!

Just yesterday upgraded to TB 78.5.0 and systray 0.5.0 is working great, no problem at all!

More than anything, thanks a lot for providing minimal packages for us "minimal desktop" people (Xfce here). Deleting more than a dozen of really unneeded packages felt very good.

Of course, this is just a stup^H^Hsmall comment on an already closed ticket, let me properly express my gratitude for your work on the project and buy you a beer! Cheers mate! :beer:
