### ISSUE TITLE
Not working with Thunderbird 78

### ISSUE THREAD

**Issue by mfreeman-xtivia** [Ximi1970/systray-x#43]
Have tried a couple of different times now and it appears that this program is broken for Thunderbird 78.

Running on Ubuntu 20.04-1

**Comment by askembris** [comment]
> Have tried a couple of different times now and it appears that this program is broken for Thunderbird 78.
> 
> Running on Ubuntu 20.04-1

It's working for me on OpenSUSE Tumbleweed with Thunderbird 78.3.1. If you are using version 0.3.0, you will need to go to your directory with the add-on files (mine was /usr/lib64/mozilla/extensions/{3550f703-e582-4d05-9a08-453d09bdfdc6}/systray-x@Ximi1970/) and change "strict_max_version" to "78.*" in manifest.json (line 11). 

I'm sure Max will update the file in the package soon enough.

**Comment by Ximi1970** [comment]
Systray-x is still working fine for version 82 beta but develop is still locked to 79 and the latest release to an even older version. I hope to fix the auto add directory feature this week, update develop and create a new version that will run on version 82.x

**Comment by mfreeman-xtivia** [comment]
The workaround of updating the manifest.json file worked for me. Thanks!!
