### ISSUE TITLE
New release to support actual version of TB

### ISSUE THREAD

**Issue by PutinVladimir** [Ximi1970/systray-x#44]
All version of TB below 78 are deprecated now. Actual is v78 so we are need new systray-x release. Even debian stable upgraded today TB to 78.3.1.

**Comment by Ximi1970** [comment]
Updated the develop branch. The max installable version is now TB 82. At the moment my virtual repos are broken and cannot test anything but openSuSE 15.2. Need to get the repos working again. Will try to create a new release this weekend.

**Comment by lgbaldoni** [comment]
0.4.0 fails on openSUSE 15.2

**Comment by Ximi1970** [comment]
That's why I have a staging repo :smile:

**Comment by Ximi1970** [comment]
Fixed.

**Comment by Ximi1970** [comment]
Now comes the testing....

**Comment by lgbaldoni** [comment]
Confirm it's fixed.

**Comment by Ximi1970** [comment]
New release 0.4.0 should work including 82.*
