### ISSUE TITLE
Separate close and minimize actions

### ISSUE THREAD

**Issue by hockeymikey** [Ximi1970/systray-x#45]
Currently seems that the minimize and close buttons do the same thing. Ideally would be great to be able to configure this so say minimize button does so to the task bar like normal and the close sends it to the status bar and removes from the taskbar. But it seems like from this issue https://github.com/Ximi1970/systray-x/issues/32 that is a known limitation and something that needs to be figured out.

**Comment by Ximi1970** [comment]
Another option coming up...But not for the current release I am planning. Still updating my test distributions....

**Comment by Ximi1970** [comment]
You can set minimize to tray in the Minimize section

**Comment by Icemole** [comment]
Yes, but that's not possible when pressing "close", I know it may sound contradictory but I believe many users use that functionality.

However, thanks for reminding me that it's on the "minimize" action, I will get used to it :)

**Comment by whtyger** [comment]
Can I upvote this suggestion?

**Comment by Icemole** [comment]
As for the project's status right now, if `Minimize -> Minimize to tray` and `Close -> Minimize all windows` are set, the behavior "works" as expected. I only use the close button, so it works for me.

**Comment by whtyger** [comment]
I see. You use different approach.

**Comment by LinAGKar** [comment]
Honestly, OP:s described behavior shouldn't even be something you need to configure it to, that should be the default. That's how pretty much all other applications with tray icons work. Changing how the minimize button works should not be the default.

**Comment by palves** [comment]
Count me in as another one who was going to report this same issue, only to find it has already been filed long ago.  I'd love for it to be possible to keep the minimize button minimizing as normal, and have the close button (on the main window) minimize to tray.  Really surprised this isn't the default.

**Comment by Ashark** [comment]
The same here. I also was surprised how strange it is implemented now.
I do not need to redefine usual minimize behavior, so when you press minimize, it should be minimized to taskbar.
I want to redefine the close button behavior, so when you press close, it should be minimized to tray.

<details>
<summary>Screenshot</summary>

![Screenshot_20230720_101211](https://github.com/Ximi1970/systray-x/assets/22634975/7db522bf-32a9-404d-bee5-0891d18342ce)
</details>

Currently, as of systray-x-kde 0.9.3-1, close to tray works only when I also redefine behavior for minimize (which I do not want).

**Comment by Ximi1970** [comment]
Added in the new release 0.9.4. The actions for minimize, close and icon click are separately programmable.
The old default actions remain (all actions to the tray). If you want to change them, do it in the preferences.

**Comment by Ashark** [comment]
@Ximi1970 Thanks.
What is "icon click"? Is it the icon of the window in the left top corner?

**Comment by Ximi1970** [comment]
Systemtray icon click

**Comment by LinAGKar** [comment]
Still plays the minimize animation when clicking the close button, but other than that it's fine now.

**Comment by Ashark** [comment]
And that minimize animation direction is to taskbar instead of to the tray.
Not a big problem though.

**Comment by Ximi1970** [comment]
I cannot change the animation in X11, they are part of the window manager. In Windows 10 or 11 it should be possible but I will not go into that rabbit hole...

**Comment by LinAGKar** [comment]
But why minimize the window before hiding it? For exampe, in WindowCtrlUnix::minimizeWindow, XIconifyWindow is called before XWithdrawWindow, and similarly in WindowCtrlWin::minimizeWindow, ShowWindow(..., SW_MINIMIZE) is called before hideWindow.

**Comment by Ximi1970** [comment]
Ah I see. I really need to check if all the window managers will accept the XWithdrawWindow only command nicely. I will have a look to refactor the minimize / hide a bit. Please be patient. I need to update all my VMs ((>30 distros) to test this a bit.
