### ISSUE TITLE
error on fedora 33 adding the repository

### ISSUE THREAD

**Issue by damnms** [Ximi1970/systray-x#46]
[root@minint-2dhlc34 oli]# dnf config-manager --add-repo https://download.opensuse.org/repositories/home:/Ximi1970:/Mozilla:/Add-ons/Fedora_33/home:Ximi1970:Mozilla:Add-ons.repo
Paketquelle von https://download.opensuse.org/repositories/home:/Ximi1970:/Mozilla:/Add-ons/Fedora_33/home:Ximi1970:Mozilla:Add-ons.repo wird hinzugefügt
Status code: 404 for https://download.opensuse.org/repositories/home:/Ximi1970:/Mozilla:/Add-ons/Fedora_33/home:Ximi1970:Mozilla:Add-ons.repo (IP: 2001:67c:2178:8::13)
Fehler: Konfiguration des Repository fehlgeschlagen

**Comment by Ximi1970** [comment]
Sorry, I still need to build the packages (100+ atm). This will take sometime. Next time I will update the README.md AFTER I uploaded the packages :-)

**Comment by Ximi1970** [comment]
If you really want to try, use the staging package:
dnf config-manager --add-repo https://download.opensuse.org/repositories/home:/Ximi1970:/Mozilla:/Add-ons:/Staging/Fedora_33/home:Ximi1970:Mozilla:Add-ons:Staging.repo

At the moment two builld problems popped up, Tumbleweed i386 and xUbuntu 20.10. Need to solve these before I can make a new release.

**Comment by Ximi1970** [comment]
Also the normal release should be available now.
