### ISSUE TITLE
Include possibility to move notification number (tray icon)

### ISSUE THREAD

**Issue by PronElle** [Ximi1970/systray-x#47]
I'd like to move the notification number to the left or right of the tray icon instead of the middle

**Comment by Ximi1970** [comment]
I can not do that. That is part of the system tray implementation.

**Comment by Ximi1970** [comment]
Oh did not read it correctly :-) (deleted my previous comment) Another option to be added.

**Comment by PronElle** [comment]
It'd be great ! Thanks =)

**Comment by PronElle** [comment]
Hi, can you please tell me when new pre-release will come out ?

**Comment by Ximi1970** [comment]
Still testing the latest x11 refactoring to get the hide from pager/switcher going. Did not realize what a mess the window managers are in. Every single one just reacts differently on some of the very basic x11 commands and events. But I think I found a way to satisfy all of them. Hopefullly the tweaks and workarounds will not bite me in the future.  
So if I do not find any strange behavior in the new setup, I could release a new version in two weeks.

**Comment by Ximi1970** [comment]
The new release 0.7.0 should solve this issue.
