### ISSUE TITLE
Can we assign a keyboard shortcut to show/hide

### ISSUE THREAD

**Issue by diegantobass** [Ximi1970/systray-x#48]
Kubuntu 20.10 - Plasma 5.19.5

I can't find a way to assign a keyboard shortcut.

**Comment by askembris** [comment]
+1 on this one, see also [this issue](https://github.com/Ximi1970/systray-x/issues/73#issuecomment-770135376)

**Comment by Ximi1970** [comment]
Added the shortcut. You can set the shortcut in the preference menu and selecting the "Shortcuts" tab.
Just press the wanted shortcut in the input field and click "Save".
I am still trying to solve a bug before creating a new release containing this feature.

**Comment by Ximi1970** [comment]
Seems like the shortcuts do not work for GNOME....Disabling it for GNOME

**Comment by Ximi1970** [comment]
New release.
