### ISSUE TITLE
[Feature request]: Facilitate translations

### ISSUE THREAD

**Issue by lgbaldoni** [Ximi1970/systray-x#49]
I know it's just a few strings, but using a service like transifex or weblate, translators would be notified when new lines need to be translated.

**Comment by Ximi1970** [comment]
Looks like both are paid service and that is a no go for me.

**Comment by Ximi1970** [comment]
If some one just translates this file, I will take care of the rest.

https://github.com/Ximi1970/systray-x/blob/develop/webext/_locales/en_US/messages.json

**Comment by askembris** [comment]
Attached the translation for Greek (I think the code is el_GR). Some of the strings are a bit long, let me know if they look horrible and need shortening.


[messages_GR.txt](https://github.com/Ximi1970/systray-x/files/5506639/messages_GR.txt)

**Comment by lgbaldoni** [comment]
@Ximi1970 as far as I understand, transifex offers a free solution for OSS products, see https://docs.transifex.com/projects/open-source-project .

Will supply the Italian translation in any case.

**Comment by Ximi1970** [comment]
Found a few strings that are not in the message file and only used on Qt. Will update the message file in an hour or so...

**Comment by lgbaldoni** [comment]
I hope I'm still in time: [SysTray-X.it.ts.txt](https://github.com/Ximi1970/systray-x/files/5507061/SysTray-X.it.ts.txt)

**Comment by Ximi1970** [comment]
Thank you all for the translations. Probably will ask for some extra lines :smile:

**Comment by Ximi1970** [comment]
@askembris could you also translate these extra lines (only the line with the message tag)?  I missed a few lines from Qt and added them now also to the messages.json. Hopefully I got everything in sync now.

Thank you,

,

  "about_title": {
    "message": "About SysTray-X",
    "description": "About box title"
  },

  "about_line_1": {
    "message": "SysTray-X Companion App by Ximi1970",
    "description": "Line 1"
  },
  
  "about_version": {
    "message": "Version:",
    "description": "Version"
  },
  
  "about_build": {
    "message": "Build:",
    "description": "Build"
  },
  
  "about_hash": {
    "message": "Hash:",
    "description": "Hash"
  },
  
  "about_branch": {
    "message": "Branch:",
    "description": "Branch"
  },

  "debug_title": {
    "message": "SysTray-X Debug",
    "description": "Debug window title"
  },

  "debug_test_1": {
    "message": "Test 1",
    "description": "Button 1"
  },

  "debug_test_2": {
    "message": "Test 2",
    "description": "Button 2"
  },

  "debug_test_3": {
    "message": "Test 3",
    "description": "Button 3"
  },

  "debug_unread": {
    "message": "Unread mail:",
    "description": "Unread label"
  },

  "menu_showhide": {
    "message": "&Show/Hide",
    "description": "Show Hide menu entry"
  },

  "menu_preferences": {
    "message": "&Preferences",
    "description": "Preferences menu entry"
  },

  "menu_about": {
    "message": "&About",
    "description": "About menu entry"
  },

  "menu_quit": {
    "message": "&Quit",
    "description": "Quit menu entry"
  },

  "menu_close": {
    "message": "Close",
    "description": "Close button"
  },
  
  "mail_notification_icon": {
    "message": "Mail notification icon",
    "description": "Mail icon selection title"
  },
  
  "number_properties": {
    "message": "Number properties",
    "description": "Number properties title"
  },

  "image_open": {
    "message": "Open image",
    "description": "File image dialog"
  },
  
  "image_files": {
    "message": "Image Files (*.png *.jpg *.bmp)",
    "description": "File image selection"
  },
  
  "image_save": {
    "message": "Save",
    "description": "File image save"
  },
  
  "image_cancel": {
    "message": "Cancel",
    "description": "File image cancel"
  }
}

**Comment by lgbaldoni** [comment]
@Ximi1970 since I used linguist-qt5 directly on the .ts file, I suspect I might have missed some string.
What do I do?

**Comment by Ximi1970** [comment]
@lgbaldoni I will have a look.

**Comment by Ximi1970** [comment]
@lgbaldoni when using the ts these lines are missing:

  "extension_description": {
    "message": "System tray control addon. Please also download the companion app.",
    "description": "Webextension descriptions"
  },
 
  "intro_line_1": {
    "message": "This addon needs an external application to work. You can get it here:",
    "description": "Introduction line 1"
  },

  "intro_link": {
    "message": "Download the SysTray-X Companion application here",
    "description": "Link description"
  },

  "accounts": {
    "message": "Accounts",
    "description": "Title for Accounts options"
  },

  "save_preferences": {
    "message": "Save preferences",
    "description": "Save preferences"
  },

  "save_preferences_button": {
    "message": "Save",
    "description": "Save preferences button"
  },


Could you also translate these? Grazie mille.

**Comment by lgbaldoni** [comment]
@Ximi1970 
[Done](https://github.com/Ximi1970/systray-x/files/5507227/systray050_extra.txt). I hope the lines aren't too long (please tell me if they are).
Also I was in doubt whether to translate the descriptions as well, but decided against it: was I wrong?

**Comment by Ximi1970** [comment]
@lgbaldoni  Only the message line is needed. So all should be complete now. Thnx!

**Comment by askembris** [comment]
Here are the rest of the messages. 

[greek_2.txt](https://github.com/Ximi1970/systray-x/files/5509830/greek_2.txt)
