### ISSUE TITLE
The Thunderbird icon is displayed in Plank dock when closing / minimizing Thunderbird to tray

### ISSUE THREAD

**Issue by logix2** [Ximi1970/systray-x#54]
Using SysTray-X 0.5.0 on Ubuntu 20.10 (Gnome), the Thunderbird icon continues to be displayed in Plank dock after it's set to close / minimize to tray. SysTray-X works correctly with Ubuntu Dock though (the Thunderbird icon is no longer displayed on Ubuntu Dock when closed / minimized to tray).

**Comment by Ximi1970** [comment]
Systray-X add-on / companion app does not remove the application icon of TB from an applcation launcher app. It will not remove the icon from the GNOME application bar or GNOME application menu, and also not from "plank" which is just another application launcher. If the Systray-X icon disappears from the SYSTEM TRAY (nomally on the top right, somewhere next to the clock) it means that TB is not running anymore.  
The Systray-X icon can look like the TB icon (no unread mail) or an icon containing the unread number of mails or any other form choosen form by the user.  
The only thing I could see is that the "red" running dot / triangle is not handled correctly in the launchers. Need to check that in the other distributions and desktops.
