### ISSUE TITLE
systray-x autostart (Arch) (84.0 b1 TB version)

### ISSUE THREAD

**Issue by fabrixx** [Ximi1970/systray-x#56]
In the build instructions i read:
```
User install:

...

System install:

...
```
in systray-x-develop/app/build i have the possibilitu to run make install with this results:
```
# make install
/usr/bin/qmake-qt5 -install qinstall -exe SysTray-X /opt/SysTray-X/bin/SysTray-X
strip /opt/SysTray-X/bin/SysTray-X
```
what is the function that binary?
The addon work well also without it?

**Comment by Ximi1970** [comment]
No it will not.  

As stated in the first line of the README:  

SysTray-X is a system tray extension for Thunderbird 68+. The addon uses the WebExtension API's to control an external system dependent system tray application.  

In other words the addon installed in TB controls an external application that will control all window / tray functions.  

So you need both installed in specific places to get it working.
Further on in the README, paragraph BUILDING:

**Comment by Ximi1970** [comment]
Th binary is the main companion app for the addon and needs to be installed in a specific place mentioned in the Systray_X.json file.

**Comment by fabrixx** [comment]
Thanks for the replies
I compiled and everything works without the make install with the steps for gnome.
When the PC restarts to be able to see the icon with the messages I have to open thunderbird and disable / reactivate the addon.
I have set boot minimized.
Is it necessary to put the binary in autostart?

**Comment by Ximi1970** [comment]
No TB will start and terminate the external companion app as long as the SysTray_X.json points in the right path, in this case the last build directory.   
But you should only use this kind of "install" for development purposes because the makefile generates the json just for the current selected build type.  
Please use an installer from the release directory if you just want to use the add-on:  
https://github.com/Ximi1970/systray-x/releases

**Comment by fabrixx** [comment]
I have Arch linux and can't find an installer that's right for me. However there is a specific version in the AUR which does not support my version of thunderbird. I am using Thunderbird nightly, I compiled and modified in the .xpi file the addon created "strict_min_version": "78.0a1" bringing it to 84 to support my version.

The addon works perfectly but I have checked this:

If I restart my PC and launch Thunderbird, the SisTray-X process starts but no icon appears.

I tried to send a test essay, Thunderbird downloads it but no icon appears.

The only way to bring up the icon is from thunderbird's addon manager, deactivate and reactivate SisTray-X.

SysTray_X.json (/ systray-x-develop / app / config / linux) points to / home / fabrixx / Desktop / systray-x-develop / app / build / SysTray-X where I actually have the binary.

I tried to uncheck start minimized but it doesn't change

I am wondering if the problem is in the unsupported Nightly version.

My problem is only the first start with thunderbird.

**Comment by Ximi1970** [comment]
There is not even a 84 beta released by TB....  I do not have the time to go bug hunting for rolling distributions that even use alfa? TB releases, sorry.

**Comment by fabrixx** [comment]
Today i turned on the pc started thunderbird 84a1 and the icon appeared.
The problem occurs only after restart, not after shutdown

**Comment by Ximi1970** [comment]
Jep TB did it again., but hey it is beta software. TB created another bug / killed another 'feature' that was still semi used in the SysTray-X and now crashes the addon. The window title is (sometimes) not retrievable anymore for whatever reason. Removed the obsolete code from SysTray-X.  
Still need to check if they killed other things.   
You can find the new code for now in the `feature-tb84` branch till I can check all repos. This is an EXPERIMENTAL branch. No guarantees this branch will work all the time or even at all.  
If you want a stable / usable system, keep away from alfa / beta software and rolling release distros.

**Comment by fabrixx** [comment]
I installed the feature-tb84 version and it works. I tried to reboot the system several times and systray-x autostart starts together with Thunderbird 84 Nightly.
