### ISSUE TITLE
Show/Hide with left button mouse click

### ISSUE THREAD

**Issue by novakmi** [Ximi1970/systray-x#57]
Thank you for this useful extension!

Currently (in XFCE), click with left button on minimized icon in tray, shows menu with Show/Hide, Preferences, ...  and click with middle button shows/hides Thunderbird. Usually, you want to show/hide Thunderbird only. As click with middle button is more difficult (click on the mouse wheel), can there be an option to show/hide directly with click left button click? This could be configured in add-on settings/Preferences.

**Comment by Ximi1970** [comment]
I had another go in trying to solve this but it is just impossible. The mouse events are handled by the different system trays and are not very flexible.

**Comment by Ximi1970** [comment]
Please be aware the left / right/ middle click actions differ in every desktop...  
It is really sad that there is no control anywhere. If you can find an example where you can switch these, please let me know.

**Comment by novakmi** [comment]
OK, thanks for trying. It's great extension, even without switched mouse buttons!
