### ISSUE TITLE
Start minimized broken

### ISSUE THREAD

**Issue by PutinVladimir** [Ximi1970/systray-x#58]
v0.6 not minimize at start.

**Comment by Ximi1970** [comment]
Strange...only happened the first time I shutdown and restarted Debian. Never happened again (5 startups).  

Please be aware that it is possible you can see a flash of a full screen TB  because the addon needs to be started before it can minimize TB.

**Comment by Ximi1970** [comment]
I add TB to the startup at login using Tweaks in Gnome and a save session in KDE

**Comment by giwrgosmant** [comment]
I can also confirm it's broken, since last night. I never had issue before. (win x64)

**Comment by Ximi1970** [comment]
Also win 10 is working for me as expected....

**Comment by giwrgosmant** [comment]
> Also win 10 is working for me as expected....

I've also did clean install on windows. It worked fine again, until the time I replied here. I made couple of restarts the PC and worked once, then again the same.
I don't know what's going on. I set Thunderbird to start up on windows like always.
The situation here is thunderbird open when Windows start up but not minimized. The problem is only on start up. 🤔

**Comment by PutinVladimir** [comment]
> Strange...only happened the first time I shutdown and restarted Debian. Never happened again (5 startups).

Behavior different:
1. Relogin KDE session and TB started minimized.
2. Close TB then Start and it is not minimized. Repeat.

**Comment by Ximi1970** [comment]
It is randomly happening on my system (more times oke then wrong but it is there...). Looks a bit like a timing problem some where, some how. Will mark it as a bug, priority one.

**Comment by Ximi1970** [comment]
The new release 0.7.0 should solve this issue.

**Comment by giwrgosmant** [comment]
> 
> 
> The new release 0.7.0 should solve this issue.

Hello,
With the new release it happens less but it's not 100% fixed. It happens again from time to time.

**Comment by Ximi1970** [comment]
As soon as I have repaired my systems, I will have another look specially for Windows. What version are you using?

**Comment by giwrgosmant** [comment]
> 
> 
> As soon as I have repaired my systems, I will have another look specially for Windows. What version are you using?

I am using version 20H2 (19042.84)

**Comment by hxss** [comment]
have this issue. "Start minimized" option not working. TB windows always open on startup. Is any extra option should be used in startup command?

* Arch x64
* xfce 4.16
* Thunderbird 78.8.1 (64-bit)
* aur/systray-x-git 0.7.0.r4.g4848769-1
