### ISSUE TITLE
Autostart on Windows causes a race condition

### ISSUE THREAD

**Issue by csolisr** [Ximi1970/systray-x#59]
When configuring Thunderbird to autostart with Windows, the tray doesn't work properly - attempting to close the application no longer minimizes or closes Thunderbird, and there's no tray displayed on the taskbar. I'm currently working around this by going to the add-on tab, disabling and re-enabling SysTray-X, which immediately minimizes Thunderbird to the taskbar as expected. I suspect this might be related to a race condition, with Thunderbird trying to minimize to tray before the companion app is opened.

OS: Windows 10 64-bit
Desktop Manager: Windows default
Thunderbird: 78.4.3 64-bit
Add-on version: 0.4.1 (will update to 0.6.0 as soon as I can reboot to Windows)
App version: 0.4.1 (same)
Install type: Github repository build
Used Qt library: as bundled with the Windows installer

**Comment by Ximi1970** [comment]
I tried 0.6, added it to the autostart folder but cannot reproduce the race condition. Everything is working as expected.
