### ISSUE TITLE
On RHEL 8.3: adding repository failed

### ISSUE THREAD

**Issue by Mack-W** [Ximi1970/systray-x#60]
When running `sudo yum-config-manager --add-repo=https://download.opensuse.org/repositories/home:/Ximi1970:/Mozilla:/Add-ons/CentOS_8/home:Ximi1970:Mozilla:Add-ons.repo` on RHEL 8.3: **404** was returned.  
Terminal Output:  
 - Updating Subscription Management repositories.
添加仓库自：https://download.opensuse.org/repositories/home:/Ximi1970:/Mozilla:/Add-ons/CentOS_8/home:Ximi1970:Mozilla:Add-ons.repo
Status code: 404 for https://download.opensuse.org/repositories/home:/Ximi1970:/Mozilla:/Add-ons/CentOS_8/home:Ximi1970:Mozilla:Add-ons.repo (IP: 195.135.221.134)
错误：配置仓库失败  

Please check the avaliability of the repository.

**Comment by Mack-W** [comment]
Both CentOS 8 and CentOS Stream repo failed.

**Comment by Ximi1970** [comment]
Can confirm, the packages are not released yet.

**Comment by Ximi1970** [comment]
Packages are now available.

**Comment by Mack-W** [comment]
Thanks.
