### ISSUE TITLE
Request support for MX Linux [Based on Debian Stable]

### ISSUE THREAD

**Issue by LinuxPanda** [Ximi1970/systray-x#61]
* OS/architecture - MX Linux (64 bit)
* Desktop/Window Manager - Xfce
* Thunderbird version/arch - 68 (64 bit)
* App version - 0.6.1
* Install type: Debian 10 OBS repository
* Used Qt library (default system repository)

```
○ → sudo apt install systray-x-minimal 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 systray-x-minimal : Depends: thunderbird (<= 1:84) but 2:68.12.0-1mx19+1 is to be installed
E: Unable to correct problems, you have held broken packages.
```
```
○ → apt policy thunderbird 
thunderbird:
  Installed: 2:68.12.0-1mx19+1
  Candidate: 2:68.12.0-1mx19+1
  Version table:
 *** 2:68.12.0-1mx19+1 500
        500 https://mirror.0x.sg/mx-workspace/mx/repo buster/main amd64 Packages
        100 /var/lib/dpkg/status
     1:78.5.0-1~deb10u1 500
        500 http://deb.debian.org/debian-security buster/updates/main amd64 Packages
     1:68.12.0-1~deb10u1 500
        500 http://mirror.0x.sg/debian buster/main amd64 Packages
```
Although MX Linux is based on Debian stable, they use their own repo for some packages and Thunderbird is one of them. So request to add support for MX Linux package naming scheme in the Debian OBS repo itself if possible or maybe a separate repo for MX Linux. Thanks.

**Comment by Ximi1970** [comment]
I tried several options to add the new epoch '2' without breaking the version limits.  
It seems just impossible to do...  
If I just cap my package with 2:84 as maximal version allowed, it is also allowing 1:100.x.x. And that is just a bad idea.  
After a lot of googling, I cannot find an option to limit the version to allow multiple ranges in different epochs like this:  
thunderbird (>= 0:68), thunderbird (<= 0:84) and  
thunderbird (>= 1:68), thunderbird (<= 1:84) and
thunderbird (>= 2:68), thunderbird (<= 2:84)  

Also the build service of opensuse does not contain MX linux as distribution so I also cannot build a special package for MX. I am afraid that you are stuck with the installer scripts.   

Will keep looking out for a solution.

**Comment by Ximi1970** [comment]
Maybe you could try install the debian thunderbird version instead of the MX one.

**Comment by LinuxPanda** [comment]
> Maybe you could try install the debian thunderbird version instead of the MX one.

Yes, that would work with apt pinning but may cause issues as they have their own apt pinning.

Maybe Ill ask the MX devs itself if its possible to add this package to their repo. Thanks.

**Comment by Ximi1970** [comment]
The only thing you have to do is:

sudo apt install thunderbird=1:78.5.0-1~deb10u1
wget -q https://download.opensuse.org/repositories/home:/Ximi1970:/Mozilla:/Add-ons/Debian_10/Release.key
sudo apt-key add Release.key
sudo bash -c 'echo "deb https://download.opensuse.org/repositories/home:/Ximi1970:/Mozilla:/Add-ons/Debian_10 ./" > /etc/apt/sources.list.d/systray-x.list'
sudo apt update
sudo apt install systray-x-minimal

The systray-x package will prevent any upgrade of thunderbird until I update the systray-x package to allow the new TB version.

**Comment by GeorgeKaragiannis** [comment]
It works perfectly! I send an email to myself and it works. But I have a problem which it doesn't have to do with the functionality. Why is there this ugly icon with the number "78" on the panel instead of thunderbird icon?  Look my screenshot.
[](https://i.postimg.cc/KYQMq7Bh/sys.png)

**Comment by Ximi1970** [comment]
You got 1782 unread mails....Why did you install this add-on???  

The main / most important thing this add-on does is displaying the number of unread mails in a tray icon....

**Comment by Ximi1970** [comment]
If you do not want the number just switch it off in the preferences and or change the icon you want.

**Comment by GeorgeKaragiannis** [comment]
@Ximi1970 OK, I found it and it looks good.
The reason I installed it is because I want to take notifications when somebody sends me an email without having thunderbird open. I'm not interested to say to me how many unread email I have.

One final question. Let's say someone has many accounts (like me); Whose account this program will show the unread emails? The first, the second, the third...?

**Comment by Ximi1970** [comment]
You can select the accounts in the add-on preferences. Thunderbird -> Tools menu -> Addons menu entry -> Systray-x -> Click the tripple dots "..." to get the menu -> Preferences menu entry -> Mail tab -> Accounts

Select the accounts / folders you want to check and click save. If you never pressed save the addon will only check the inboxes of all the accounts.
