### ISSUE TITLE
Windows: Cannot resize Thunderbird when using minimize to tray

### ISSUE THREAD

**Issue by Ximi1970** [Ximi1970/systray-x#62]
1) The Thunderbird window cannot be resized when SysTray-X is active.  
A restart of TB is needed after disabling the plugin to get the resize action back.  

2) Close button action not restored when disabling the plugin.  

OS: Windows 10 64-bit
Desktop Manager: Windows default
Thunderbird: 78.5.0 64-bit
Add-on version: 0.6.1
Install type: Github 64bit windows package
Used Qt library: as bundled with the Windows installer

**Comment by Ximi1970** [comment]
And on another system it works, WTF?

**Comment by se10dev** [comment]
> And on another system it works, WTF?
I had a similar behavior with another addon some months ago, although I don't remeber which one it was. Odd side-effects from a user perspective, but this procedure worked for me:
Manually update and then disable all addons, close Thunderbird, delete session + cache, start Thunderbird, restart once more, then reenable addons one by one with restarting Thunderbird for each and check if resize works. Maybe this helps and if not, at least you will know for sure which addon is causing it.

**Comment by Ximi1970** [comment]
Was only my plugin installed...So I have work to do :-)

**Comment by Ximi1970** [comment]
The new release 0.7.0 should solve this issue.
