### ISSUE TITLE
Tray icon displays New rather than Unread messages

### ISSUE THREAD

**Issue by mjeveritt** [Ximi1970/systray-x#63]
The old FireTray had an option to show you the number of New messages in the mailbox, as an alternative to the total Unread messages in the mailbox. I'm not sure whether this was calculated as 'new messages seen arrive' or 'new messages' by some other (IMAP/etc?) method.

I think the facility exists here already to pick whether it's New/Unread messages in the root Inbox folder, or includes all subfolders, but these two options would be most useful to users I think.

**Comment by Ximi1970** [comment]
The new release 0.7.0 should solve this issue.
