### ISSUE TITLE
[Feature request]: Exclude Thunderbird from task switcher when in tray

### ISSUE THREAD

**Issue by lgbaldoni** [Ximi1970/systray-x#64]
As per subject, it would be nice not to see pop it up with alt-tab when minimised in the tray.

Using openSUSE Leap 15.2 with plasma5: do you see a way around that?

**Comment by fabianski7** [comment]
This was something I could do in previous versions of thunderbird + systray-x, has anything changed on the thunderbird side?

For those who use plasma, you can create a rule to ignore thunderbird from alt+tab. Just go to the Kwin settings and create a rule for that.
[Something like this
](https://upload.vaa.red/hba2G#xgJzVlF5s2UMTUIOmHqIXdHreEF4ZPGM
)

**Comment by Ximi1970** [comment]
@fabianski7 thanks for the workaround.  

Removing TB from the taskbar should also remove it from the alt+tab but that is not happening. Still looking if I missed an extra x11 flag, or if I am using a wrong order to hide the window, or it is a change in the desktop managers.  
Also got some problems managing two (or more) desktops and were TB gets restored.   
Going to refactor the x11 part a bit I think.

**Comment by lgbaldoni** [comment]
@fabianski7 could you please export LANG=en_US.UTF-8 afore launching systemsettings? 🥺

**Comment by Ximi1970** [comment]
@lgbaldoni seems like plasma just disregards all default x11 flags for the hiding (SKIP_TASKBAR and SKIP_PAGER) in the task switcher. I added also the SKIP_PAGER flag but the switcher does not care. The only thing that "works" is changing the window type to "DOCKER" but when I try to restore the Thunderbird window to "NORMAL" it wreaks havoc in the plasma window administration and I loose all connections to that window and reacts a bit weird afterwards, so that is not usable.  
I am afraid I cannot solve this for now. Still hope to stumble upon a workaround...

**Comment by lgbaldoni** [comment]
@Ximi1970 😕
Regarding the kwin script, do you have a recipe? I think I've managed to decipher the Portuguese screenshot above, but now the window is stuck open without a tray😬

**Comment by Ximi1970** [comment]
@lgbaldoni  That is the same I got when I tried to change the window type....Looks like a bug in plasma?

**Comment by Ximi1970** [comment]
There are more strange behaviors of plasma in Leap 15.2. Like windows start always opening at 0,0

**Comment by Ximi1970** [comment]
With twin screen and disabling a monitor. It will reset the positions of your desktop icons and put them all in a line on top row.   
It is quiet annoying at the moment.....

**Comment by lgbaldoni** [comment]
Do you think this and the problem with X11 are worth testing against Tumbleweed?

**Comment by Ximi1970** [comment]
Always :-) I hope to intercept new "changes" before they get to the main release. I am updating Thumble right now to start a test session.

**Comment by Ximi1970** [comment]
Just found this when searchong SKIP_SWITCHER : https://forum.kde.org/viewtopic.php?f=111&t=91102  

Mailing list reply from Martin <kde()martin-graesslin!com>:

    No, we discussed it when implementing it and decided that this is not a
    usecase for an atom and not something an application should control.

Sometimes I do not understand the reasenng of some developers.
So there is no way around the problem...

**Comment by Ximi1970** [comment]
You can use the workaround of @fabianski7 but Thunderbird will never be in the switcher as long as the rule is active.  
You can setup a new rule this way:

(openSuSE 15.2)
System settings -> (Workspace) Window Management -> (Sidebar) Window Rules -> Click "New..."  

(Tab) Window matching:
Description: Thunderbird
Window types: Only "normal window"
Window title: Substring match "Thunderbird"

(Tab) Arrangement & access:
Mark Skip switcher, apply initially, select "Yes"

Click "OK"
Click "Apply" in the Window Rules

Restart Thunderbird.

**Comment by lgbaldoni** [comment]
With these settings:
![kwin_1](https://user-images.githubusercontent.com/1450716/103171508-31326500-484d-11eb-9b12-1318b2a479ff.jpg)
![kwin_2](https://user-images.githubusercontent.com/1450716/103171509-342d5580-484d-11eb-83b8-465f17aaa298.jpg)

The system tray icon disappears when closing the window.

Launching from console I see:
```
~> thunderbird 
*** Error in `/usr/bin/SysTray-X': corrupted size vs. prev_size: 0x000055ee973e04f0 ***
```

**Comment by lgbaldoni** [comment]
Uh oh, I'm using 0.6.1, should I switch to trunk?

**Comment by Ximi1970** [comment]
Found also another problem when you press the TB "icon" on the taskbar.  Hiding goes wrong...  
But I do not get the close error. But I am using the feature-x11 packages from my Test2 repository

**Comment by Ximi1970** [comment]
At the moment this repo has the feature-x11 branch (and that can change time I need another test package:
https://download.opensuse.org/repositories/home:/Ximi1970:/Mozilla:/Add-ons:/Staging:/Test2/openSUSE_Leap_15.2/

This one contains the packages based upon "develop":
https://download.opensuse.org/repositories/home:/Ximi1970:/Mozilla:/Add-ons:/Staging:/Test/openSUSE_Leap_15.2/

**Comment by fabianski7** [comment]
> ![kwin_1](https://user-images.githubusercontent.com/1450716/103171508-31326500-484d-11eb-9b12-1318b2a479ff.jpg)

It seems that you are using an old version of plasma, this rules window was remade a long time ago. Maybe that's why you're having trouble.

> Sometimes I do not understand the reasenng of some developers.
So there is no way around the problem...

I think this may be related to some security concerns. It makes sense to want to avoid that programs can be hidden in this way, despite breaking the functionality of some extensions like systray-x.

At least kwin rules do an alternative job that also works. For me it's enough.

**Comment by Ximi1970** [comment]
@fabianski7 these are the setup windows for the default 15.2 release....Yours are in Tumbleweed. I am really not going to mix "previews" in my main SuSE release. Plasma contains already to many bugs for me...Even thinking to go back to 15.1

**Comment by Ximi1970** [comment]
@fabianski7 security reasons still do not explain why the switcher, which is just another pager, is ignoring the default x11 flags like the SKIP_PAGER.

**Comment by fabianski7** [comment]
> @fabianski7 these are the setup windows for the default 15.2 release....Yours are in Tumbleweed. I am really not going to mix "previews" in my main SuSE release. ~Plasma~ 15.2 contains already to many bugs for me...Even thinking to go back to 15.1

I'm using the 5.20.4 plasma in archlinux, it's pretty stable for me.



> @fabianski7 security reasons still do not explain why the switcher, which is just another pager, is ignoring the default x11 flags like the SKIP_PAGER.

Some programs that I use can still be started in a minimized way, like QOwnNotes and KeePassXC, Ksnip. All in qt... Maybe it's some features of this framework?

**Comment by lgbaldoni** [comment]
@Ximi1970 
>  At the moment this repo has the feature-x11 branch (and that can change any time I need another test package:
https://download.opensuse.org/repositories/home:/Ximi1970:/Mozilla:/Add-ons:/Staging:/Test2/openSUSE_Leap_15.2/

Tried that one and the kwin script indeed works.
What doesn't work is the number of unread messages, which is shown to be 5 instead of 26.

What's worse is that reinstalling 0.6.1 did not solve the problem! 🤯

**Comment by Ximi1970** [comment]
@fabianski7  thanks for the examples, will have a look at these to see if I missed something somewhere :smile:   
 
I am using a dual screen system with a double nvidia at the moment because the current Leap 15.2 / Plasma / Kernel cannot handle the Intel / nVidia virtualization at all anymore. Found a workaround I could somehow live with :smiley: (that is a dual nVidia and a special kernel) but still my icons get a reset everytime I switch one monitor on and off. Stopped setting the icons back....Still need to look if Tumbleweed still has the same problem.  
15.1 worked nicely the way I wanted with the Intel / nVidia drivers and default desktop.

**Comment by Ximi1970** [comment]
@lgbaldoni sorry forgot to mention I also changed the message filtering in that branch due to translation problems.  
There is also a extra option now: show New messages. Only shows the newly arrived messages.  
You probably need to check the accounts settings again and press save.

**Comment by Ximi1970** [comment]
@lgbaldoni only made a one way conversion for the filters...

**Comment by lgbaldoni** [comment]
@Ximi1970 with "New messages" I get zero unread. With "unread" I see just 5, unsure how they are counted.

I have two accounts with several nested folders.

**Comment by Ximi1970** [comment]
@lgbaldoni reselect the account and foldersin the settings  and press save. Restart Thunderbird.

**Comment by lgbaldoni** [comment]
@Ximi1970 thanks, that did the trick.

**Comment by Ximi1970** [comment]
@fabianski7 these examples are all pure Qt applications. Problem is that Thunderbird is not. And I can only manipulated the TB window using X11 / Window Manager. And if they do not obey the X11 commands / flags I can not do anything.  
The Qt part of the add-on, the companion app is working perfectly if you look at the switcher part.  It is a system tray application that hides nicely and is not visible as long as you do not open the preferences or enable the debug menu.   
So no solution can be found in these sadly enough....
May be I can have another look at the KDocker application. Thats is more like how systray-x works.

**Comment by Ximi1970** [comment]
The new release 0.7.0 should solve this issue.

**Comment by fabianski7** [comment]
thanks!
