### ISSUE TITLE
Tb restores to the desktop where it was started

### ISSUE THREAD

**Issue by katonagl** [Ximi1970/systray-x#65]
I have a multi desktop setup in KDE. If I minimize Tb to tray, switch to another desktop and then restore Tb from the tray, it takes me to the original desktop and restores Tb there. However I think Tb should always restore to the current desktop, since I am working there and just want to check/write an email, after which Tb goes back to tray.

One solution could be, to make Tb visible on all desktops, but this is not convenient, because there are cases when I leave Tb open on one desktop and go for another one to do some tasks.

Firetray did this trick. Is it possible to implement in systray-x?

**Comment by Ximi1970** [comment]
What is your Distribution / Desktop environment?

**Comment by katonagl** [comment]
openSUSE Tumbleweed 20201205
KDE Plasma: 5.20.4
KDE Frameworks: 5.76.0
Qt: 5.15.2

**Comment by Ximi1970** [comment]
Fixed in the feature-x11 branch (refactor of the x11 Systray-x part)  but needs a bit of testing this week before I commit it to develop. If it is in develop I will create a new release with all the change from the past weeks.

**Comment by katonagl** [comment]
Great news, thanks. Waiting for it. 
Sorry for asking here, but do you aware of the following annoying bug? https://github.com/Ximi1970/systray-x/issues/40

**Comment by Ximi1970** [comment]
#40 Never ever happened to me on Leap 15.2. And I have 20 accounts with the inbox selected and one account with 50 sub folders selected. So low prio for me right now.

**Comment by Ximi1970** [comment]
The new release 0.7.0 should solve this issue.
