### ISSUE TITLE
Official (upstream/unstable) Debian package

### ISSUE THREAD

**Issue by amaramrahul** [Ximi1970/systray-x#68]
Considering that you have arleady built a debian package, did you consider packing this for upstream Debian? Considering the number of distributions dervied from Debian, this would be reaching a large audience.

**Comment by Ximi1970** [comment]
If they would keep their packages the same, it would be a lot easier...  
I need to figure out the new dependency again.

**Comment by Ximi1970** [comment]
The new release 0.7.0 should solve this issue.
