### ISSUE TITLE
Subfolders completely broke with 0.7.0

### ISSUE THREAD

**Issue by fdellwing** [Ximi1970/systray-x#71]
I still need to enable subfolders after every start (#40), but since yesterdays 0.7.0 update the functionality broke completely.

No mails in subfolders are counted at all, only the Inbox works.

```
Kubuntu 18.04.5
TB 68.12.0 x64
systray-x 0.7.0
```

I downgraded to 0.6.1 because I need this thing to work.

**Comment by Ximi1970** [comment]
Did you ever use the script installers of SysTray-X?  

Tried everything in my Kubuntu 18.04 (latest updates installed, but the standard TB is 68.10.0) using my repository for Ubuntu 18.04.  
Everything is just working fine. Switched KDE to german, no problems except that TB stays English. Forcing it to German also no problems.  

So where did you get your TB version?  Are you using the Mozilla binary?

**Comment by fdellwing** [comment]
I have the problem with 68.10.0 and 68.12.0, I updated it after 0.7.0 did not work. The newer version is from the official mozillateam PPA => https://launchpad.net/~mozillateam/+archive/ubuntu/ppa

systray-x was ever installed via .DEB and updated via apt.

**Comment by Ximi1970** [comment]
Also installed the PPA. Still cannot replicate the problem. Everything is working just fine with a clean Virtualbox install.

**Comment by fdellwing** [comment]
Problem is gone with TB78.
