### ISSUE TITLE
0.7.0 Not Working on KDE Neon 5.20

### ISSUE THREAD

**Issue by mfreeman-xtivia** [Ximi1970/systray-x#72]
Updated to new 0.7.0 and had all kinds of issues on KDE Neon. New email arrivals not reflected in tray icon, cannot click on the tray icon, and a host of others.

Tried both the blow-by-blow instructions in the README as well as the deb-based install with no joy in either of them.

Reverted back to 0.6.1 which i have been using forever and its all good again.

This is a brand new fresh copy of Neon downloaded and installed yesterday

**Comment by Ximi1970** [comment]
KDE Neon probably switched to plasma Wayland as default? This add-on will never work in a FULL Wayland desktops due to the chosen design of Wayland.

I updated my (10 months old) KDE Neon distros (took 10 hours, every time again amazed by the slooooww update of ubuntu distros)  and SysTray-X is just working fine in both (18.04 based and 20.04 based) using the x11 plasma setup.

**Comment by mfreeman-xtivia** [comment]
But 0.6.1 works just fine on KDE Neon (latest) oob. Have seen this now on 2 different systems.

**Comment by mfreeman-xtivia** [comment]
And FWIW i Plasma Wayland is planned for 5.21 so its not here yet

**Comment by Ximi1970** [comment]
It is already in the distro. You can select it in 5.19.4 and 5.20.5 in the login screen. But even in these setups Systray-X is just working fine so they are not fully wayland and still contain some form of the x11 event handling the plugin needs.  

Keep in mind I will only test standard distro installs.    

I will download the latest version of Kde Neon and setup a third Virtualbox image.

**Comment by Ximi1970** [comment]
Which of the 4 releases are you using of Neon?

**Comment by mfreeman-xtivia** [comment]
![image](https://user-images.githubusercontent.com/10734467/105551274-1de9ac80-5cc8-11eb-800d-8337a4f4559e.png)

**Comment by Ximi1970** [comment]
Installed a fresh version of Neon in Virtualbox. Installed the default Thunderbird (68.10.0) and systray-x from the SysTray-X repo of xUbuntu 20.04.  
No problems found.

**Comment by mfreeman-xtivia** [comment]
Feel free to close it then--but its very repeatable here on clean copies of Neon, systray-x 0.7.0. And does not happen with 0.6.1. For me i will just have to stay on 0.6.1 and disable the ppa for updates.....but thanks for taking the time to check

**Comment by Ximi1970** [comment]
Tested again with 5.22.5 and the develop Systray-x version. Still working as expected.
