### ISSUE TITLE
Tb is minimized to tray after switching desktop (KDE)

### ISSUE THREAD

**Issue by katonagl** [Ximi1970/systray-x#74]
When Tb is maximized (visible) and I switch to another desktop (or activity) and back under KDE, Tb gets minimized to tray (this is the action for the close and minimize buttons), but it should stay open.

OpenSUSE Tumbleweed 64bit 20210121
KDE Plasma: 5.20.5
KDE Frameworks: 5.78.0
Qt: 5.15.2
Thunderbird: 78.6.1 64bit
Systray-X: 0.7.0, installed by script from github

**Comment by pablo-blueoakdb** [comment]
I'm witnessing the same behavior.with Tumbleweed at the head (and the latest TBird).

**Comment by pablo-blueoakdb** [comment]
I noticed if I disable the Add-On, TB does not minimize.  I hope the additional data helps.

**Comment by pablo-blueoakdb** [comment]
For me, the problem only happens when I am VNCd and I switch to another desktop.  Is` that the same for you @katonagl ?

 I'm going to try and fiddle with my VNC Server settings.

**Comment by pablo-blueoakdb** [comment]
My C is very rusty and my GUI skills are non-existent.  Undeterred, I've made a little progress in capturing debug data to the debug console.

When I'm VNCd, I see the following in the console:
```
Updatex11: WinID 56623120, state: normal
State x11: 3
Minimize
Withdraw window
Minimize done
```
Tomorrow I'll try to capture more debug information to determine why the code thinks we should minimize rather than ignore the Virtual Desktop switch via VNC.

**Comment by pablo-blueoakdb** [comment]
Temporary relief until I get a chance to debug.  In `windowctrl-unix.cpp`

```
/*
 *  Minimize a window
 */
void    WindowCtrlUnix::minimizeWindow( quint64 window )
{
#ifdef DEBUG_DISPLAY_ACTIONS
    emit signalConsole( "Minimize" );
#endif
    emit signalConsole( "I don't think so!" ); // pablo
    return; // pablo -- make this a no-op - total hack
```

**Comment by McNobody** [comment]
I had same problem with Fluxbox, Thunderbird 78.13.0, SysTray-X 0.8.0 at Ubuntu 20.04 LTS.

When changing virtual desktop back to Thunderbird desktop, Thunderbird is minimized.

I disabled minimizing like pablo and now I can live with SysTray-X again. I really like to have SysTray-X to see count of new messages at tray icon.
