### ISSUE TITLE
Drag and drop of messages doesn't work in GNOME.

### ISSUE THREAD

**Issue by jfbits** [Ximi1970/systray-x#77]
The drag and drop of messages doesn't work on Fedora 33.

**Comment by Ximi1970** [comment]
Uh this addon or the plugin does not do anything with drag and drop... And please if you want to post a bug, be more informative and post at least:

Please start your bug report mentioning at least:

    OS and architecture used (32 or 64 bit)
    Desktop / Window Manager (KDE, Xfce, Cinnamon, MATE etc)
    Thunderbird version and arch (32 or 64 bit)
    Add-on version
    App version
    Install type: github repository build, script installer, OBS repository.
    Used Qt library (default system repository, other OBS repo, self-compiled, Qt online installer)

Bug description, how to reproduce, what you expect to happen.

Thank you for reporting!

**Comment by hetau** [comment]
OS and architecture used (Fedora 33, 64 bit)
Desktop / Window Manager (Gnome 3.38.3)
Thunderbird version and arch (64 bit)
Add-on version (0.7.0)
App version (78.7.0)
Install type: Fedora repository.
Used Qt library (default system repository)

When the add-on is active and start the Thunderbird the messages drag and drop doesn't work.
But if the add-on is disable and start the Thunderbird the messages drag and drop work, i can drag and drop the emails to the folders I want.

Thanks in advanced

**Comment by araujorm** [comment]
Same here. Fortunately it doesn't affect another addon I have that provides me the functionality to move the messages to other locations (Quick Folder Move), so I can live with that for the moment. However it's still an unexpected behavior that may be disruptive to several people.

**Comment by scarlehoff** [comment]
Same problem here:

Using:
 Arch Linux
 Gnome 40.1 (Xorg)
 Add-on 0.7.0, Build 710
 Thunderbird 78.10.1

Happy to provide any other information.

**Comment by Ximi1970** [comment]
Did a bit more investigations. Strangely enough drag and drop is working fine on my main system but also works when running in a Virtualbox guest (ubuntu 20.04 and Leap) on this system.  
But as soon as I run it on my repository test platform in a Virtualbox guest via a vnc session it does not work. any more  
Both systems have an nVidia GPU, same Leap version, same nVidia driver.
Also no problems with an Intel / Optimus laptop.  

@hetau , @scarlehoff what kind of GPU and x11 video drivers are you using? Maybe this will shed some light at the problem but it looks like some problem with the some of the x11 graphics drivers.

**Comment by Ximi1970** [comment]
New release!
