### ISSUE TITLE
Tray icon and overall functionality broken on Arch KDE

### ISSUE THREAD

**Issue by hockeymikey** [Ximi1970/systray-x#78]
I'm using the most recent 0.7.0 and for awhile now it has been busted for me. The tray icon is there, but it doesn't do anything. Right clicking doesn't work, nor does left clicking. If I right click about 40 seconds after I get the right click dialog appearing (sometimes it's just random without the right click). The minimizing doesn't work either or closing either. Only can minimize to the tray, that's the only thing it can do. It's like the installation or something is corrupted and even with re installations it persists. Any ideas how to tackle this?

**Comment by Ximi1970** [comment]
Checked it and the repository version is just working fine with the latest updates .
