### ISSUE TITLE
Restore maximized window state after hiding to tray

### ISSUE THREAD

**Issue by hxss** [Ximi1970/systray-x#79]
* Arch x64
* xfce 4.16
* Thunderbird 78.8.1 (64-bit)
* aur/systray-x-git 0.7.0.r4.g4848769-1

After hiding maximized window to tray TB restores in normal state. Systray-x restores any normal window size/position but not maximized state. On startup window state restores correctly.

**Comment by duguyipiao** [comment]
As a workaround, you can enable the title bar, i.e., disable the client-side decoration.

**Comment by Ximi1970** [comment]
Seems to be just working fine with 0.8.0 and 91.2.0. Can you have a look?

**Comment by duguyipiao** [comment]
> Seems to be just working fine with 0.8.0 and 91.2.0. Can you have a look?

Not for me when CSD is enabled.
Manjaro Xfce, thunderbird 91.2.0, and the latest dev commit 9da01b8b2e757ae338c2d7fbbbe8df3d85d9449c

**Comment by Ximi1970** [comment]
Uh what is CSD?

**Comment by Ximi1970** [comment]
Ah found it. :smile: Looks like you are disabling the hooks I need to control the TB window.

**Comment by Ximi1970** [comment]
@hxss please have a look if the problem still exists. My window is still maximized when it was docked before.
