### ISSUE TITLE
Mail count not working in TB 87 throught TB 89

### ISSUE THREAD

**Issue by Ximi1970** [Ximi1970/systray-x#81]
TB change the API's again. FolderChange is not working anymore.

**Comment by cement-head** [comment]
Affects me as well...

**Comment by Ximi1970** [comment]
Has been fixed in branch feature-fix-tb86 but only works for Tb 87 - Tb 89.  
Tb 90  and higher has more API changes that broke the count mechanism, see: https://github.com/Ximi1970/systray-x/issues/88   
I think I will hold merging the fix_tb86 branch until I find also a solution for Tb 90 and higher.  
These are still TB alpha versions. they do not deserve the beta status.
