### ISSUE TITLE
Repository key expired?

### ISSUE THREAD

**Issue by fdellwing** [Ximi1970/systray-x#82]
```
Err:10 https://download.opensuse.org/repositories/home:/Ximi1970:/Mozilla:/Add-ons/xUbuntu_20.04 ./ InRelease
  The following signatures were invalid: EXPKEYSIG BEEF5C3607D86FE9 home:Ximi1970 OBS Project <home:Ximi1970@build.opensuse.org>
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://download.opensuse.org/repositories/home:/Ximi1970:/Mozilla:/Add-ons/xUbuntu_20.04 ./ InRelease: The following signatures were invalid: EXPKEYSIG BEEF5C3607D86FE9 home:Ximi1970 OBS Project <home:Ximi1970@build.opensuse.org>
W: Failed to fetch https://download.opensuse.org/repositories/home:/Ximi1970:/Mozilla:/Add-ons/xUbuntu_20.04/./InRelease  The following signatures were invalid: EXPKEYSIG BEEF5C3607D86FE9 home:Ximi1970 OBS Project <home:Ximi1970@build.opensuse.org>
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by sasha-** [comment]
pub   rsa2048 2017-01-19 [SC] [**expired: 2021-05-24**]
      01A5D4EFE73D0F34F8253112BEEF5C3607D86FE9
uid           home:Ximi1970 OBS Project <home:Ximi1970@build.opensuse.org>

**Comment by cement-head** [comment]
Can someone fix the repo key...or is this project dead?

**Comment by manojbaishya** [comment]
Until the key is renewed, disabling the software source will hide errors.

![image](https://user-images.githubusercontent.com/28330014/120143926-aa6c2480-c1fe-11eb-982c-dba827d90557.png)

**Comment by Ximi1970** [comment]
I cannot find a way to update the key in the repo. Still trying different ways to get it renewed...  
But I have a work-around for now, please use this key:

`
wget -q https://download.opensuse.org/repositories/home:/Ximi1970/xUbuntu_20.04/Release.key
`

**Comment by Ximi1970** [comment]
Looks like it took some time to update. The keys in home:Ximi1970:Mozilla:Add-ons are now also updated.
