### ISSUE TITLE
Tray icon doesn't work

### ISSUE THREAD

**Issue by bitchecker** [Ximi1970/systray-x#83]
Hi,
I've installed the fedora rawhide repo and I tried to send some mail from myself and I've seen the counter on the tray. 

After that test, I can't see any more counter when Thunderbird is not minimized and if filters move mail to directories.

Could you please take a look at this behavior:
- have a counter both minimized and opened window
- count new mails also when they were filtered

**Comment by Ximi1970** [comment]
Please have a look at #4 and provide all the info.

**Comment by bitchecker** [comment]
- OS and architecture used (32 or 64 bit)

Fedora 34 64bit

- Desktop / Window Manager (KDE, Xfce, Cinnamon, MATE etc)

XFCE


- Thunderbird version and arch (32 or 64 bit)

78.11.0 (64 bit)

- App version

systray-x-minimal-0.6.1-2.71

- Install type: github repository build, script installer, OBS repository.

home:Ximi1970:Mozilla:Add-ons.repo

- Used Qt library (default system repository, other OBS repo, self-compiled, Qt online installer)

default system repository

**Comment by Ximi1970** [comment]
Can you have a look if 0.8.0 still has this problem? If you are hiding the title bar this is a known issue.
