### ISSUE TITLE
Thunderbird X close button doesn't do anything after installing SystrayX on Debian10/KDE

### ISSUE THREAD

**Issue by mYnDstrEAm** [Ximi1970/systray-x#86]
I'm running Debian10/KDE and installed SystrayX like [this](https://github.com/Ximi1970/systray-x#debian). When I started Thunderbird afterwards the X close button in the upper right doesn't do anything and does not [minimize Thunderbird to the tray](https://unix.stackexchange.com/questions/656489/how-to-minimize-thunderbird-to-tray-in-gnu-linux-debian).

There isn't any systrayx in the tray even after running `/usr/bin/SysTray-X`. I don't think that it's a problem with AppArmor.

Is this a known problem? How to solve this?

**Comment by Ximi1970** [comment]
I tested it again in a cleanly installed Debian / KDE. It is just working fine.

**Comment by mYnDstrEAm** [comment]
Ok, thanks for testing it. It must be caused by something else like AppArmor then. I'll try to find out by what.

**Comment by mYnDstrEAm** [comment]
it's due to AppArmor /var/log/syslog has this:
```
kernel: [...] audit: type=1400 audit(...): apparmor="DENIED" operation="ptrace" profile="thunderbird//sanitized_helper" pid=[...] comm="SysTray-X" requested_mask="read" denied_mask="read" peer="thunderbird"
```
How to make it work with AppArmor?

`sudo apparmor_status` shows:
```
[...] processes are in enforce mode.
   /usr/lib/thunderbird/thunderbird-bin ([...]) thunderbird
```

**Comment by Ximi1970** [comment]
Sorry, I do not know. Never had any problems with the default setup of AppArmor. Luckily never had to change anything. It is a configuration monstrosity....

**Comment by mYnDstrEAm** [comment]
Asked about it [here](https://unix.stackexchange.com/questions/663153/how-to-configure-apparmor-to-allow-minimizing-thunderbird-to-the-tray-on-debian), maybe somebody knows more about it.

**Comment by mYnDstrEAm** [comment]
It's still not working after upgrading to Debian 11 and the latest systray-x update. Clicking on the X button does nothing and there's no output in the console. There's still many entries about apparmor in the syslog. In Thunderbird version of Systray is 0.8.0. The addon Enigmail is installed as well.

**Comment by Ximi1970** [comment]
Default setup for Debian Gnine is wayland. Please switch to X11

**Comment by Ximi1970** [comment]
Checked again but works just fiine.

Fresh install Debian 11, make sure to select the Xorg Gnome when logging in. Install the package from the repo, logout and login.
![Screenshot_20211002_175655](https://user-images.githubusercontent.com/859953/135723821-1547e9af-0195-4585-b9e6-b6652c32e205.png)

**Comment by mYnDstrEAm** [comment]
I'm using KDE (as written) and am already using X11 (kwin_x11).

**Comment by Ximi1970** [comment]
Checked also with a fresh install of Debian 11 with KDE instead of Gnome. Still working without any problems.
![Screenshot_20211002_214406](https://user-images.githubusercontent.com/859953/135729943-503db9f4-04d1-43cf-82c2-274d9ae2f49f.png)

**Comment by mYnDstrEAm** [comment]
Thanks, really strange, I'll try to debug further - it seems to be a problem with AppArmor but that's enabled by default in Debian 11 so it should have also occurred there. The Thunderbird I have installed is 1:78.14.0-1~deb11u1, apparmor is 2.13.6-10 and apparmor-profiles also 2.13.6-10.

**Comment by Ximi1970** [comment]
I got the same thunderbird and apparmor but the profiles are not installed in the clean version.

**Comment by Ximi1970** [comment]
Installed the profiles. Still no problems.

**Comment by mYnDstrEAm** [comment]
Birdtray works now after upgrading to Debian11 (the question linked in the original post is solved now).

Couldn't determine why it didn't work. I also tried disabling all addons. There is no new syslog entry after clicking the X button. There are 3 apparmor error message when opening thunderbird for whatever reasons, these are:

```
audit: ... apparmor="DENIED" operation="open" profile="thunderbird" name="/proc/sys/dev/i915/perf_stream_paranoid" pid=... comm="thunderbird" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
audit: type=1400 audit(...): apparmor="DENIED" operation="open" profile="thunderbird" name="/proc/.../cgroup" pid=... comm="thunderbird" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000
audit: type=1400 audit(...): apparmor="DENIED" operation="ptrace" profile="thunderbird//sanitized_helper" pid=.... comm="SysTray-X" requested_mask="read" denied_mask="read" peer="thunderbird"
```

(and I launched thunderbird without firejail). Anyways, I also consider this issue closed now as the solution was to simply use birdtray.
