### ISSUE TITLE
Mail count disappeared after 78.12.0 update

### ISSUE THREAD

**Issue by lgbaldoni** [Ximi1970/systray-x#87]
Using openSUSE Leap 15.3.

**Comment by paul-w42** [comment]
I can confirm this.

**Comment by Ximi1970** [comment]
I can only confirm that the account filters got reset (again?) for some reason. After setting the filters again, count works just fine on my 15.3.
I need to remove the filter checking...Does more damage then good.
Sadly enough I had very little time the past months. And still have not the time to dive into this. Please hang on :smile:

**Comment by lgbaldoni** [comment]
I don't understand how this could happen. Isn't the API supposed to remain stable on ESR updates? Kind of the whole point of it?

**Comment by Yonn-Trimoreau** [comment]
Thunderbird's development team seems completely unaware of the "retro-compatibility" term.

**Comment by Yonn-Trimoreau** [comment]
That's mainly why I personally donate to Thunderbird's extension maintainers, and I encourage everyone to do so. Hard job maintaining an extension in an ecosystem that doesn't give a shit about maintainability.

**Comment by Ximi1970** [comment]
@Yonn-Trimoreau, thank you for your donation and support! :+1:  
Every new TB release is a surprise :yum: 
But also a few rolling release distributions do not make this an easy job.

**Comment by lgbaldoni** [comment]
I just installed 0.8.0 from `home:Ximi1970:Mozilla:Add-ons:Staging` on Leap 15.3 and unfortunately the mail count is still off (it goes up to 1 after a while, but it doesn't seem responsive to reading/unreading messages).

Also the Preferences window cannot be resized and at least with the Italian locale, some strings are cut.

**Comment by Ximi1970** [comment]
@lgbaldoni Checked the `home:Ximi1970:Mozilla:Add-ons` version with a clean Leap 15.3.It is just working fine (this should be the same as the staging version).  
You can try the new `reset preferences` button in the TB preferences menu to clear all old settings in TB.  
You need to setup all the preferences of Systray-x again afterwards.  
Also when you are going to use TB 91 you need to do this because I switch the storage type due to the new limitations from TB.

**Comment by lgbaldoni** [comment]
Resetting preferences seems to do the trick, although it now takes a while for the number of unread messages to appear.

**Comment by Ximi1970** [comment]
You can reduce the startup delay in the preferences menu but the newer thunderbirds probably need the delay because the account information is not available on startup and will mess up the filter and count setup.

**Comment by lgbaldoni** [comment]
Thanks, it works now. Will wait for the official 91 package, whenever that may come.
