### ISSUE TITLE
Mail count does not work in Tb 90 and higher due to (again) API changes

### ISSUE THREAD

**Issue by Ximi1970** [Ximi1970/systray-x#88]
Tb developers seem keen to loose add-on developers and users by continuously changing the API.  
Internal folder handling has been changed again.
Need to find a solution and change the count mechanisme again.  
Use the new functions added in the TB91 Web extensions API?  

onFolderInfoChanged
https://webextension-api.thunderbird.net/en/latest/folders.html#folders-getparentfolders

Was previously unusable...

**Comment by Ximi1970** [comment]
Tb 91.0b6 storage and account API broken / unstable.

**Comment by Ximi1970** [comment]
API call getFolderInfo(folder) not working in Tb91.0bx

**Comment by atomGit** [comment]
temp work-a-round in my case is to open the add-on settings and re-select folders to monitor, save settings

**Comment by Ximi1970** [comment]
They also decide to change the storage, it looks like TB91 beta still worked but in the release it is impossible to save the settings.
Tb starts one or two times oke but then loses the storage and accounts on startup. Strange...


Error: QuotaExceededError: storage.sync API call exceeded its quota limitations.

**Comment by Ximi1970** [comment]
And.....impossible to install the old TB. Great job again.....

**Comment by Ximi1970** [comment]
Looks like the account info is not fully available at startup of the plugin. Folders are missing of random accounts. Delaying the call seems to work. Need to build in a timer again for startup.  
We are back at TB pre 61...

**Comment by lgbaldoni** [comment]
Any news? Should I postpone upgrading to tb91.x until this is fixed?

Also, would you recommend using the snapshot for the time being?

**Comment by Ximi1970** [comment]
Looks like I tackled all the problems but I still need to clean it up and test it a bit. TB  internally and externally changed the account and folder api  and usage. They also changed the handling of the embedded javascripts so things got a bit scrambled. I needed to force the used promises into submission and into a nice timed sequence to get all the data in the right place at the right time. And keep every thing compatible with the old versions.    
Still not committed to the github feature-fix-tb9x branch.  
The SysTray-X package installed using a repository will block any upgrade to a newer TB version until I release a new version that I think will work (at least on my daily system).  
If you are updating manually,  Systray-X will not work anymore. And you cannot go back to the previous version of TB due to a internal TB files / DB upgrade. So if you want to try MAKE A BACKUP OF YOUR TB CONFIG DIR.

I do not see any reasons to update to TB91.

**Comment by Ximi1970** [comment]
Still storage problems when trying to save a lot of filters....

**Comment by Ximi1970** [comment]
Looks like storage space has been limited to 16384 bytes for an add-on. Need to find a way to increase the storage limitations, or limit the number of filters that can be defined and optimize it a bit.

**Comment by Ximi1970** [comment]
Oops looks like I am using the wrong storage :smile:

**Comment by katonagl** [comment]
Short question. When do you plan to release an initial beta of systray-x working with Tb91? Unfortunately I have upgraded and now no systray-x. Shall I struggle with downgrade or will you release something in the next few days?

**Comment by Ximi1970** [comment]
I am not planning any releases the next few days. I need to refactor the javascript part a bit due to the new changes made in TB90+.  

As soon as I get the code working again nicely on my system (openSUSE Leap 15.3, KDE) I will update it to the feature-fix-tb9x branch. Be aware that I give no support if you want to try that code. After I am convinced I tackled all the problems, I will test it on more distributions and then eventually I will merge it into develop.

**Comment by atomGit** [comment]
@Ximi1970  - until the fix is in, what worked for me is to set and save the options (folders to scan) for systray-x each time you start t-bird

**Comment by Ximi1970** [comment]
Yes the problem at the moment is storage (limited now to 16384 bytes) and the changes in the folders API. (Wrong inbox path is saved)
I solved both problems but I want also to refactor the filters part so it will use less storage space.  
Hopefully I can finish the refactoring this weekend.  
Still thinking on how to move the data from the 'sync' storage to the "local" storage or leave it to the user deciding which one to use. Did not realize the sync storage would be used for syncing between TB instances probably and I am a bit concerned about privacy there.  
There is, I think, still no syncing of data between Thunderbird instances as is possible in Firefox.
