### ISSUE TITLE
No repo for Fedora 34

### ISSUE THREAD

**Issue by christophehenry** [Ximi1970/systray-x#89]
Fedora 34 has been released for a few months now but there's no `systray-x` repo targeting Fedora 34. While F33's repo is still working for now, it may break in the future.

**Comment by Ximi1970** [comment]
I already was testing Fedora 34. Seems like it just works fine with Gnome. I enabled the repo and updated the README.md

**Comment by christophehenry** [comment]
Working fine on KDE too. Thank you for your work :+1:
