### ISSUE TITLE
systray-x closing

### ISSUE THREAD

**Issue by fabianski7** [Ximi1970/systray-x#9]
OS and architecture used: archlinux 5.4.26-1-lts 64-bit
Thunderbird version and arch: 64 bit
Add-on version: 0.1
App version: 68.6.0 
Used Qt library: default system repository

When you close the thunderbird message composer, the systray-x is closed as well.

[video](https://upload.vaa.red/VCVvj#MfYrHXh8wYAR2h2gpQTY2EZzxSxaRU8f)

**Comment by Ximi1970** [comment]
Fixed in develop and feature-release-test branch
