### ISSUE TITLE
Config file?

### ISSUE THREAD

**Issue by DUOLabs333** [Ximi1970/systray-x#93]
I use KDE with a 250% display scaling, so most QT-based configuration windows are too big for me to click "OK" to save (Recoll has the same problem). So, is there a config file to save the preferences to?

**Comment by Ximi1970** [comment]
Tb is not Qt based, but you should always be able to scroll the preferences window down and or sideways so you can see and click the save.

**Comment by DUOLabs333** [comment]
I was referring to the "Preferences" window that Systray-X has.

**Comment by Ximi1970** [comment]
Please use the TB SysTray-X addon preference window if you cannot use the icon preference dialog. It also has the account and folder configuration options.

**Comment by DUOLabs333** [comment]
Oh great! I didn't see that (i use Dark Reader, and it inverted the colors of the tabs).
