### ISSUE TITLE
Will there be a new release? 

### ISSUE THREAD

**Issue by PutinVladimir** [Ximi1970/systray-x#97]
subj

**Comment by DUOLabs333** [comment]
There is a branch that is involved in fixing the extension for 9x, though I'm not sure how far along is it.

**Comment by DUOLabs333** [comment]
I just tried it out, and it seems to work pefectly.

**Comment by Ximi1970** [comment]
Working on it :smile: Taming the scripts and updating all distributions. Still need to install Debian 11.    
Please be aware that all preferences will get lost when using the new version with TB91.

**Comment by Ximi1970** [comment]
Released 0.8.0
