### ISSUE TITLE
Minimize on startup not working for Windows with TB90+

### ISSUE THREAD

**Issue by Ximi1970** [Ximi1970/systray-x#98]
TB90+ does not start minimized when selected.

**Comment by mi16087** [comment]
It does not work on EndeavourOS KDE plasma also :D

**Comment by angrysquirell** [comment]
It's really strange. On Arch Linux with Xfce without saving session sometimes TB starts with tray icon, sometimes not. Don't know what it depends on.

**Comment by Ximi1970** [comment]
New release!
