### ISSUE TITLE
Building for Solus OS with Bungie desktop

### ISSUE THREAD

**Issue by afettouhi** [Ximi1970/systray-x#99]
As the title says, is it possible to build systray-x for SolusOS with the Bungie desktop? I tried to build it from git but I can't get the tray icon to show up. Many thanks for this app btw. Still can't understand Thunderbird has refused for so so many years to implement this.

**Comment by Ximi1970** [comment]
Make sure all the tools are installed: git, make, binutils, g++, qt5-base-devel, libx11-devel, zip. Hopefully I did not forget one. It is  a very bare OS.  

Open a terminal and type (as mentioned in the README at the bottom `Build (GNOME)`::  

git clone https://github.com/Ximi1970/systray-x.git  
cd systray-x  
make OPTIONS="DEFINES+=NO_KDE_INTEGRATION"  
mkdir -p ~/.mozilla/native-messaging-hosts  
cp -f app/config/linux/SysTray_X.json ~/.mozilla/native-messaging-hosts/  

Startup Thunderbird.  
Goto Tools -> Add-ons -> Click the gear on the right ->  Install add-on from file.  
Navigate to the git systray-x directory and select the `systray-x@Ximi1970.xpi` file.  
Restart Thunderbird to use the default settings (only the inbox will be checked).  
The icon will appear on the bottom right next to the other icons.

**Comment by Ximi1970** [comment]
![image](https://user-images.githubusercontent.com/859953/135530404-4aa218ce-8f92-427d-b7c8-e21e1bbdc048.png)

**Comment by afettouhi** [comment]
Thanks that worked! Awesome!
